-- GENERATED by scripts/build_bridge.py from lua/src/*.lua - do not edit by hand.
-- >>> 00_core.lua
-- REAPER MCP bridge - core: JSON, handle registry, object resolution, helpers.
-- Source file; bundled into lua/mcp_bridge.lua by scripts/build_bridge.py.

H = {}          -- handler table: H.<tool_func> = function(p) ... end   (p = named params)

-- ============================================================================
-- JSON + handle registry
-- ============================================================================

-- Arrays carry their length in a metatable so nil holes survive round trips
-- (table.unpack(args) would otherwise stop at the first JSON null).
local ARRAY_MT = {}
local function json_array(t, n)
    return setmetatable(t, {__index = ARRAY_MT, __n = n or #t})
end
local function array_len(t)
    local mt = getmetatable(t)
    if mt and mt.__n then return mt.__n end
    return #t
end

-- Handle registry: userdata (MediaItem*, MediaTrack* ...) returned to the client
-- is encoded as {"__ptr": "<id>"}; when the client sends it back we resolve it to
-- the real pointer again, after validating it is still alive (a stale pointer
-- passed to the API can crash REAPER).
local HANDLES = {}
local HANDLE_TYPES = {"MediaItem_Take*", "MediaItem*", "MediaTrack*", "TrackEnvelope*",
                      "ReaProject*", "PCM_source*"}

local function register_handle(v)
    local key = tostring(v)
    HANDLES[key] = v
    return key
end

local function resolve_handle(t)
    local p = HANDLES[t.__ptr]
    if p == nil then error("Unknown handle " .. tostring(t.__ptr) .. " (bridge restarted?)") end
    for _, ty in ipairs(HANDLE_TYPES) do
        if reaper.ValidatePtr2(0, p, ty) then return p end
    end
    -- PCM sources etc. are not always project-validated; accept if ValidatePtr knows the type
    for _, ty in ipairs(HANDLE_TYPES) do
        if reaper.ValidatePtr(p, ty) then return p end
    end
    HANDLES[t.__ptr] = nil
    error("Stale handle " .. tostring(t.__ptr) .. " (object was deleted)")
end

local function resolve_args(args)
    local n = array_len(args)
    for i = 1, n do
        local a = args[i]
        if type(a) == "table" and a.__ptr then args[i] = resolve_handle(a) end
    end
    return n
end

local function encode_string(s)
    -- Escape quotes, backslashes and every control char. If the string is not
    -- valid UTF-8 (binary MIDI messages, chunk data), escape high bytes as
    -- \u00XX so the client can recover the exact bytes via latin-1.
    local valid = utf8.len(s) ~= nil
    local out = s:gsub('[%c"\\\128-\255]', function(c)
        if c == '"' then return '\\"'
        elseif c == '\\' then return '\\\\'
        elseif c == '\n' then return '\\n'
        elseif c == '\r' then return '\\r'
        elseif c == '\t' then return '\\t'
        end
        local b = c:byte()
        if b >= 128 and valid then return c end
        return string.format('\\u%04x', b)
    end)
    return '"' .. out .. '"'
end

-- JSON null that can live inside Lua tables (nil can't): keeps keys present in tool output
NULL = setmetatable({}, {__tostring = function() return "null" end})
local function nullable(v) if v == nil then return NULL end return v end

local function encode_json(v)
    local tv = type(v)
    if tv == "nil" or v == NULL then
        return "null"
    elseif tv == "boolean" then
        return tostring(v)
    elseif tv == "number" then
        if v ~= v or v == math.huge or v == -math.huge then return "null" end
        if math.type(v) == "integer" then return tostring(v) end
        return string.format("%.17g", v)
    elseif tv == "string" then
        return encode_string(v)
    elseif tv == "table" then
        local parts = {}
        local mt = getmetatable(v)
        local n = (mt and mt.__n) or #v
        if n > 0 or (mt and mt.__n) then
            for i = 1, n do parts[i] = encode_json(v[i]) end
            return "[" .. table.concat(parts, ",") .. "]"
        end
        for k, item in pairs(v) do
            parts[#parts + 1] = encode_string(tostring(k)) .. ":" .. encode_json(item)
        end
        return "{" .. table.concat(parts, ",") .. "}"
    elseif tv == "userdata" then
        return '{"__ptr":' .. encode_string(register_handle(v)) .. '}'
    end
    return "null"
end

-- Recursive-descent JSON decoder (strings may contain any of , [ ] { } ").
local function decode_json(str)
    if not str or str == "" then return nil end
    local pos = 1
    local function ws() pos = str:find("[^ \t\r\n]", pos) or #str + 1 end
    local value
    local function err(msg) error("JSON decode error at " .. pos .. ": " .. msg) end
    local function parse_string()
        pos = pos + 1
        local buf = {}
        while true do
            local c = str:sub(pos, pos)
            if c == "" then err("unterminated string") end
            if c == '"' then pos = pos + 1; break end
            if c == "\\" then
                local e = str:sub(pos + 1, pos + 1)
                if e == "u" then
                    local cp = tonumber(str:sub(pos + 2, pos + 5), 16)
                    if not cp then err("bad \\u escape") end
                    pos = pos + 6
                    -- surrogate pair
                    if cp >= 0xD800 and cp <= 0xDBFF and str:sub(pos, pos + 1) == "\\u" then
                        local lo = tonumber(str:sub(pos + 2, pos + 5), 16)
                        if lo and lo >= 0xDC00 and lo <= 0xDFFF then
                            cp = 0x10000 + (cp - 0xD800) * 0x400 + (lo - 0xDC00)
                            pos = pos + 6
                        end
                    end
                    buf[#buf + 1] = utf8.char(cp)
                else
                    local map = {n = "\n", r = "\r", t = "\t", b = "\b", f = "\f", ['"'] = '"', ["\\"] = "\\", ["/"] = "/"}
                    buf[#buf + 1] = map[e] or e
                    pos = pos + 2
                end
            else
                local s, e2 = str:find('^[^"\\]+', pos)
                buf[#buf + 1] = str:sub(s, e2)
                pos = e2 + 1
            end
        end
        return table.concat(buf)
    end
    value = function()
        ws()
        local c = str:sub(pos, pos)
        if c == "{" then
            pos = pos + 1
            local obj = {}
            ws()
            if str:sub(pos, pos) == "}" then pos = pos + 1; return obj end
            while true do
                ws()
                if str:sub(pos, pos) ~= '"' then err("expected key") end
                local k = parse_string()
                ws()
                if str:sub(pos, pos) ~= ":" then err("expected ':'") end
                pos = pos + 1
                obj[k] = value()
                ws()
                local d = str:sub(pos, pos); pos = pos + 1
                if d == "}" then return obj end
                if d ~= "," then err("expected ',' or '}'") end
            end
        elseif c == "[" then
            pos = pos + 1
            local arr, n = {}, 0
            ws()
            if str:sub(pos, pos) == "]" then pos = pos + 1; return json_array(arr, 0) end
            while true do
                n = n + 1
                arr[n] = value()
                ws()
                local d = str:sub(pos, pos); pos = pos + 1
                if d == "]" then return json_array(arr, n) end
                if d ~= "," then err("expected ',' or ']'") end
            end
        elseif c == '"' then
            return parse_string()
        elseif str:sub(pos, pos + 3) == "true" then pos = pos + 4; return true
        elseif str:sub(pos, pos + 4) == "false" then pos = pos + 5; return false
        elseif str:sub(pos, pos + 3) == "null" then pos = pos + 4; return nil
        else
            local s, e = str:find("^-?%d+%.?%d*[eE]?[-+]?%d*", pos)
            if not s then err("unexpected '" .. c .. "'") end
            pos = e + 1
            return tonumber(str:sub(s, e))
        end
    end
    local ok, res = pcall(value)
    if not ok then
        reaper.ShowConsoleMsg("MCP bridge: " .. tostring(res) .. "\n")
        return nil
    end
    return res
end

-- ============================================================================
-- Generic helpers
-- ============================================================================

local function round(x) return math.floor(x + 0.5) end

-- list(t) marks a Lua sequence as a JSON array (also when empty)
local function list(t) return json_array(t or {}, #(t or {})) end

local function fail(msg, ...) error(string.format(msg, ...), 0) end

local function opt(v, default) if v == nil then return default end return v end

local function db_to_gain(db) return 10 ^ (db / 20) end
local function gain_to_db(g) if g <= 0 then return -math.huge end return 20 * math.log(g, 10) end
local function db_out(g)    -- JSON can't hold -inf
    local d = gain_to_db(g); if d == -math.huge then return -150.0 end; return d
end

local function color_to_native(c)
    if c == nil or c == false or c == "" then return 0 end
    local r, g, b = c:match("^#?(%x%x)(%x%x)(%x%x)$")
    if not r then fail("color must be '#rrggbb', got %s", tostring(c)) end
    return reaper.ColorToNative(tonumber(r, 16), tonumber(g, 16), tonumber(b, 16)) | 0x1000000
end

local function color_from_native(n)
    if not n or n & 0x1000000 == 0 then return NULL end
    local r, g, b = reaper.ColorFromNative(n & 0xFFFFFF)
    return string.format("#%02x%02x%02x", r, g, b)
end

-- run fn inside one undo block (and without UI refresh); returns fn's result
local function undoable(desc, fn)
    reaper.Undo_BeginBlock2(0)
    reaper.PreventUIRefresh(1)
    local ok, res = pcall(fn)
    reaper.PreventUIRefresh(-1)
    reaper.Undo_EndBlock2(0, "MCP: " .. desc, -1)
    reaper.UpdateArrange()
    if not ok then error(res, 0) end
    return res
end

local function guid_of_track(tr) return reaper.GetTrackGUID(tr) end
local function guid_of_item(it)
    local _, g = reaper.GetSetMediaItemInfo_String(it, "GUID", "", false); return g
end

-- ============================================================================
-- Object resolution (index / GUID / name)
-- ============================================================================

local function track_index(tr)
    if tr == reaper.GetMasterTrack(0) then return -1 end
    return math.tointeger(reaper.GetMediaTrackInfo_Value(tr, "IP_TRACKNUMBER")) - 1
end

-- track ref: integer index (0-based, -1 = master), GUID "{...}", or exact track name
local function get_track(ref)
    if ref == nil then fail("track is required") end
    if type(ref) == "number" then
        if ref == -1 then return reaper.GetMasterTrack(0) end
        local tr = reaper.GetTrack(0, ref)
        if not tr then fail("no track at index %d (project has %d tracks)", ref, reaper.CountTracks(0)) end
        return tr
    end
    if type(ref) == "string" then
        if ref:match("^{.*}$") then
            for i = 0, reaper.CountTracks(0) - 1 do
                local tr = reaper.GetTrack(0, i)
                if reaper.GetTrackGUID(tr) == ref then return tr end
            end
            fail("no track with GUID %s", ref)
        end
        local found
        for i = 0, reaper.CountTracks(0) - 1 do
            local tr = reaper.GetTrack(0, i)
            local _, name = reaper.GetTrackName(tr)
            if name == ref then
                if found then fail("more than one track is named '%s' - use the index", ref) end
                found = tr
            end
        end
        if found then return found end
        fail("no track named '%s'", ref)
    end
    if type(ref) == "userdata" then return ref end
    fail("bad track reference %s", tostring(ref))
end

-- item ref: project-wide index (0-based) or GUID
local function get_item(ref)
    if ref == nil then fail("item is required") end
    if type(ref) == "number" then
        local it = reaper.GetMediaItem(0, ref)
        if not it then fail("no item at index %d (project has %d items)", ref, reaper.CountMediaItems(0)) end
        return it
    end
    if type(ref) == "string" then
        for i = 0, reaper.CountMediaItems(0) - 1 do
            local it = reaper.GetMediaItem(0, i)
            if guid_of_item(it) == ref then return it end
        end
        fail("no item with GUID %s", ref)
    end
    if type(ref) == "userdata" then return ref end
    fail("bad item reference %s", tostring(ref))
end

local function item_index(it)
    for i = 0, reaper.CountMediaItems(0) - 1 do
        if reaper.GetMediaItem(0, i) == it then return i end
    end
    return -1
end

-- take ref on an item: index, -1/nil = active take
local function get_take(item, ref)
    local take
    if ref == nil or ref == -1 then take = reaper.GetActiveTake(item)
    else take = reaper.GetMediaItemTake(item, ref) end
    if not take then fail("item has no take %s", tostring(ref or "(active)")) end
    return take
end

local function get_midi_take(p)
    local item = get_item(p.item)
    local take = get_take(item, p.take)
    if not reaper.TakeIsMIDI(take) then fail("take is not MIDI") end
    return item, take
end

local function check_time(t, what)
    if type(t) ~= "number" then fail("%s must be a number (seconds)", what) end
    return t
end


-- >>> 01_api.lua
do
-- reaper_api: call any ReaScript function by name (the long tail not covered by domain tools).
-- Pointers returned by REAPER come back as {"__ptr": "..."} handles and can be passed back.

H.reaper_api = function(p)
    local fname = p.func
    if type(fname) ~= "string" or reaper[fname] == nil then
        fail("unknown ReaScript function '%s'", tostring(fname))
    end
    local args = p.args or json_array({}, 0)
    local n = resolve_args(args)
    local res = table.pack(reaper[fname](table.unpack(args, 1, n)))   -- errors propagate as tool errors
    local vals = {}
    for i = 1, res.n do vals[i] = res[i] end
    return {ret = json_array(vals, res.n)}
end

H.ping = function()
    return {version = reaper.GetAppVersion(), bridge = 2}
end

end
-- >>> 05_actions_util.lua
do
-- Run a main-section action only if REAPER's name for that id contains `expect` (guards
-- against wrong/changed command ids doing something else).
function RUN_CHECKED_ACTION(id, expect)
    local name = reaper.kbd_getTextFromCmd(id, reaper.SectionFromUniqueID(0)) or ""
    if not name:lower():find(expect:lower(), 1, true) then
        error(string.format("action %d is '%s', expected '%s' - not run", id, name, expect), 0)
    end
    reaper.Main_OnCommand(id, 0)
end

end
-- >>> 10_project.lua
do
-- Project, tabs, undo

local function proj_path()
    local _, path = reaper.EnumProjects(-1)
    return path or ""
end

local function current_tab_index()
    local cur = reaper.EnumProjects(-1)
    local i = 0
    while true do
        local proj = reaper.EnumProjects(i)
        if not proj then return -1 end
        if proj == cur then return i end
        i = i + 1
    end
end

H.project_info = function(p)
    local _, num, den = 0, 4, 4
    num, den = reaper.TimeMap_GetTimeSigAtTime(0, 0)
    local ts_start, ts_end = reaper.GetSet_LoopTimeRange(false, false, 0, 0, false)
    local n_mark, n_markers, n_regions = reaper.CountProjectMarkers(0)
    local srate_use = reaper.GetSetProjectInfo(0, "PROJECT_SRATE_USE", 0, false) == 1
    return {
        name = reaper.GetProjectName(0, ""),
        path = proj_path(),
        dirty = reaper.IsProjectDirty(0) ~= 0,
        tab_index = current_tab_index(),
        length = reaper.GetProjectLength(0),
        bpm = reaper.Master_GetTempo(),
        time_signature = string.format("%d/%d", num, den),
        tempo_markers = reaper.CountTempoTimeSigMarkers(0),
        sample_rate = srate_use and reaper.GetSetProjectInfo(0, "PROJECT_SRATE", 0, false) or NULL,
        tracks = reaper.CountTracks(0),
        items = reaper.CountMediaItems(0),
        markers = n_markers, regions = n_regions,
        cursor = reaper.GetCursorPosition(),
        time_selection = {start = ts_start, ["end"] = ts_end},
        reaper_version = reaper.GetAppVersion(),
    }
end

H.project_save = function(p)
    if p.path then
        if not p.path:lower():match("%.rpp$") then fail("path must end with .rpp") end
        reaper.Main_SaveProjectEx(0, p.path, 0)
    else
        if proj_path() == "" then fail("project has never been saved - pass a path (avoids a Save As dialog)") end
        reaper.Main_SaveProject(0, false)
    end
    return {path = proj_path(), dirty = reaper.IsProjectDirty(0) ~= 0}
end

H.project_notes = function(p)
    if p.text ~= nil then
        reaper.GetSetProjectNotes(0, true, p.text)
        reaper.MarkProjectDirty(0)
    end
    return {text = reaper.GetSetProjectNotes(0, false, "")}
end

local function undo_step(redo)
    local can = redo and reaper.Undo_CanRedo2(0) or reaper.Undo_CanUndo2(0)
    if not can then fail("nothing to %s", redo and "redo" or "undo") end
    local ok = redo and reaper.Undo_DoRedo2(0) or reaper.Undo_DoUndo2(0)
    if ok == 0 then fail("%s failed", redo and "redo" or "undo") end
    return {[redo and "redone" or "undone"] = can,
            next_undo = reaper.Undo_CanUndo2(0), next_redo = reaper.Undo_CanRedo2(0)}
end
H.project_undo = function(p) return undo_step(false) end
H.project_redo = function(p) return undo_step(true) end

H.project_tabs = function(p)
    local tabs, cur, i = {}, reaper.EnumProjects(-1), 0
    while true do
        local proj, path = reaper.EnumProjects(i)
        if not proj then break end
        tabs[#tabs + 1] = {index = i, name = reaper.GetProjectName(proj, ""), path = path,
                           current = proj == cur, dirty = reaper.IsProjectDirty(proj) ~= 0}
        i = i + 1
    end
    return {tabs = list(tabs)}
end

H.project_new_tab = function(p)
    reaper.Main_OnCommand(40859, 0)     -- File: New project tab
    return {tab_index = current_tab_index()}
end

H.project_select_tab = function(p)
    local proj = reaper.EnumProjects(p.index or -2)
    if not proj then fail("no project tab %s", tostring(p.index)) end
    reaper.SelectProjectInstance(proj)
    return {tab_index = current_tab_index(), name = reaper.GetProjectName(proj, "")}
end

-- Close the current tab. Never risks REAPER's modal "save changes?" dialog (which would block
-- the bridge): with save_path the project is saved there first; an unsaved, modified project
-- is refused.
H.project_close_tab = function(p)
    if p.save_path then
        H.project_save({path = p.save_path})
        -- Main_SaveProjectEx writes the file but leaves the tab "modified"; re-open the saved file
        -- in this tab without prompting so it is clean and closes without a dialog.
        reaper.Main_openProject("noprompt:" .. p.save_path)
    end
    if reaper.IsProjectDirty(0) ~= 0 then
        fail("project has unsaved changes - pass save_path, or save it first")
    end
    local i = current_tab_index()
    reaper.Main_OnCommand(40860, 0)     -- File: Close current project tab
    return {closed_tab = i, tab_index = current_tab_index()}
end

end
-- >>> 11_transport.lua
do
-- Transport and edit cursor

local function state()
    local ps = reaper.GetPlayState()
    local playing = ps & 1 ~= 0
    return {
        playing = playing, paused = ps & 2 ~= 0, recording = ps & 4 ~= 0,
        position = (playing or ps & 2 ~= 0) and reaper.GetPlayPosition() or reaper.GetCursorPosition(),
        cursor = reaper.GetCursorPosition(),
        repeat_enabled = reaper.GetSetRepeat(-1) == 1,
    }
end

H.transport_state = function(p) return state() end
H.transport_play = function(p) reaper.OnPlayButton(); return state() end
H.transport_stop = function(p) reaper.OnStopButton(); return state() end
H.transport_pause = function(p) reaper.OnPauseButton(); return state() end
H.transport_record = function(p) reaper.Main_OnCommand(1013, 0); return state() end  -- Transport: Record

H.transport_set_cursor = function(p)
    reaper.SetEditCurPos(check_time(p.position, "position"), opt(p.move_view, true), opt(p.seek_play, true))
    return state()
end

H.transport_set_repeat = function(p)
    reaper.GetSetRepeat(p.enabled and 1 or 0)
    return state()
end

end
-- >>> 12_time.lua
do
-- Time selection, loop, grid, position conversion

H.time_selection_get = function(p)
    local s, e = reaper.GetSet_LoopTimeRange(false, false, 0, 0, false)
    local ls, le = reaper.GetSet_LoopTimeRange(false, true, 0, 0, false)
    -- "Options: Loop points linked to time selection": when on, setting one sets both
    return {time_selection = {start = s, ["end"] = e}, loop = {start = ls, ["end"] = le},
            linked = reaper.GetToggleCommandState(40621) == 1}
end

H.time_selection_set = function(p)
    local s, e = check_time(p.start, "start"), check_time(p["end"], "end")
    if e < s then fail("end must be >= start") end
    local target = opt(p.target, "time_selection")
    if target ~= "time_selection" and target ~= "loop" and target ~= "both" then
        fail("target must be time_selection, loop or both")
    end
    if target ~= "loop" then reaper.GetSet_LoopTimeRange(true, false, s, e, false) end
    if target ~= "time_selection" then reaper.GetSet_LoopTimeRange(true, true, s, e, false) end
    return H.time_selection_get({})
end

-- Convert a position given as seconds, quarter notes, or measure(+beat) (1-based, as REAPER
-- displays them) into all representations.
H.time_convert = function(p)
    local t
    if p.seconds ~= nil then t = p.seconds
    elseif p.qn ~= nil then t = reaper.TimeMap2_QNToTime(0, p.qn)
    elseif p.measure ~= nil then
        t = reaper.TimeMap2_beatsToTime(0, (p.beat or 1) - 1, p.measure - 1)
    elseif p.text ~= nil then t = reaper.parse_timestr_pos(p.text, -1)
    else fail("give one of seconds, qn, measure(+beat) or text") end
    local beat, measure, cml, fullbeats, cdenom = reaper.TimeMap2_timeToBeats(0, t)
    local num, den, bpm = reaper.TimeMap_GetTimeSigAtTime(0, t)
    return {
        seconds = t, qn = reaper.TimeMap2_timeToQN(0, t),
        measure = math.tointeger(measure) + 1, beat = beat + 1, full_beats = fullbeats,
        time_signature = string.format("%d/%d", num, den), bpm = bpm,
        text_measures = reaper.format_timestr_pos(t, "", 2),
        text_time = reaper.format_timestr_pos(t, "", 0),
    }
end

local function grid_state()
    local _, division, swingmode, swingamt = reaper.GetSetProjectGrid(0, false, 0, 0, 0)
    return {division = division, swing = swingmode == 1, swing_amount = swingamt,
            snap = reaper.GetToggleCommandState(1157) == 1}
end

H.grid_get = function(p) return grid_state() end

-- division in whole notes: 0.25 = quarter, 0.125 = eighth, 1/12 = eighth triplet ...
H.grid_set = function(p)
    local g = grid_state()
    local division = opt(p.division, g.division)
    if division <= 0 then fail("division must be > 0 (fraction of a whole note, e.g. 0.25)") end
    local swing = opt(p.swing, g.swing)
    reaper.GetSetProjectGrid(0, true, division, swing and 1 or 0, opt(p.swing_amount, g.swing_amount))
    if p.snap ~= nil and p.snap ~= g.snap then reaper.Main_OnCommand(1157, 0) end
    return grid_state()
end

end
-- >>> 13_tempo.lua
do
-- Tempo and time signature

local function marker(i)
    local _, t, measure, beat, bpm, num, den, lin = reaper.GetTempoTimeSigMarker(0, i)
    local m = {index = i, time = t, measure = measure + 1, beat = beat + 1, bpm = bpm,
               linear = lin, qn = reaper.TimeMap2_timeToQN(0, t)}
    if num > 0 then m.time_signature = string.format("%d/%d", num, den) end
    return m
end

H.tempo_map_get = function(p)
    local out = {}
    for i = 0, reaper.CountTempoTimeSigMarkers(0) - 1 do out[#out + 1] = marker(i) end
    local num, den, bpm = reaper.TimeMap_GetTimeSigAtTime(0, 0)
    return {markers = list(out), project_bpm = reaper.Master_GetTempo(), start_bpm = bpm,
            start_time_signature = string.format("%d/%d", num, den)}
end

-- points: [[time, bpm, num(0=no change), den, linear], ...] or [{time, bpm, num, den, linear}]
H.tempo_map_set = function(p)
    local points = p.points or json_array({}, 0)
    return undoable("set tempo map", function()
        if opt(p.clear, true) then
            for i = reaper.CountTempoTimeSigMarkers(0) - 1, 0, -1 do reaper.DeleteTempoTimeSigMarker(0, i) end
        end
        if p.base_bpm then reaper.SetCurrentBPM(0, p.base_bpm, false) end
        local n, added = array_len(points), 0
        for i = 1, n do
            local q = points[i]
            local t, bpm, num, den, lin
            if q.time ~= nil then t, bpm, num, den, lin = q.time, q.bpm, q.num, q.den, q.linear
            else t, bpm, num, den, lin = q[1], q[2], q[3], q[4], q[5] end
            if reaper.SetTempoTimeSigMarker(0, -1, t, -1, -1, bpm, num or 0, den or 0, lin and true or false) then
                added = added + 1
            end
        end
        reaper.UpdateTimeline()
        if added ~= n then fail("REAPER accepted %d of %d tempo points", added, n) end
        return {markers = added}
    end)
end

H.tempo_marker_add = function(p)
    local t = check_time(p.time, "time")
    if not p.bpm then fail("bpm is required") end
    return undoable("add tempo marker", function()
        if not reaper.SetTempoTimeSigMarker(0, -1, t, -1, -1, p.bpm, p.num or 0, p.den or 0, p.linear and true or false) then
            fail("REAPER rejected the tempo marker")
        end
        reaper.UpdateTimeline()
        local i = reaper.FindTempoTimeSigMarker(0, t + 1e-9)
        return marker(i)
    end)
end

H.tempo_marker_set = function(p)
    local i = p.index
    if type(i) ~= "number" or i < 0 or i >= reaper.CountTempoTimeSigMarkers(0) then fail("no tempo marker %s", tostring(i)) end
    local _, t, measure, beat, bpm, num, den, lin = reaper.GetTempoTimeSigMarker(0, i)
    return undoable("edit tempo marker", function()
        reaper.SetTempoTimeSigMarker(0, i, opt(p.time, t), -1, -1, opt(p.bpm, bpm),
            opt(p.num, num), opt(p.den, den), opt(p.linear, lin))
        reaper.UpdateTimeline()
        return marker(reaper.FindTempoTimeSigMarker(0, opt(p.time, t) + 1e-9))
    end)
end

H.tempo_marker_delete = function(p)
    local i = p.index
    if type(i) ~= "number" or i < 0 or i >= reaper.CountTempoTimeSigMarkers(0) then fail("no tempo marker %s", tostring(i)) end
    undoable("delete tempo marker", function() reaper.DeleteTempoTimeSigMarker(0, i); reaper.UpdateTimeline() end)
    return {markers = reaper.CountTempoTimeSigMarkers(0)}
end

-- project tempo without markers (with markers present, edit them via tempo_marker_set)
H.tempo_set = function(p)
    if not p.bpm or p.bpm < 1 or p.bpm > 960 then fail("bpm must be 1..960") end
    if reaper.CountTempoTimeSigMarkers(0) > 0 then
        fail("project has tempo markers - use tempo_marker_set / tempo_map_set instead")
    end
    reaper.SetCurrentBPM(0, p.bpm, true)
    reaper.UpdateTimeline()
    return {bpm = reaper.Master_GetTempo()}
end

end
-- >>> 20_track.lua
do
-- Tracks

local function track_name(tr)
    if tr == reaper.GetMasterTrack(0) then return "MASTER" end
    local _, name = reaper.GetTrackName(tr)
    return name
end

local function V(tr, k) return reaper.GetMediaTrackInfo_Value(tr, k) end

local function track_summary(tr)
    return {
        index = track_index(tr),
        name = track_name(tr),
        guid = reaper.GetTrackGUID(tr),
        folder_depth = math.tointeger(V(tr, "I_FOLDERDEPTH")),
        volume_db = db_out(V(tr, "D_VOL")),
        pan = V(tr, "D_PAN"),
        mute = V(tr, "B_MUTE") == 1,
        solo = V(tr, "I_SOLO") ~= 0,
        arm = V(tr, "I_RECARM") == 1,
        auto_arm = V(tr, "B_AUTO_RECARM") == 1,
        selected = V(tr, "I_SELECTED") == 1,
        color = color_from_native(math.tointeger(V(tr, "I_CUSTOMCOLOR"))),
        fx_count = reaper.TrackFX_GetCount(tr),
        item_count = reaper.CountTrackMediaItems(tr),
    }
end

H.track_list = function(p)
    local out = {}
    for i = 0, reaper.CountTracks(0) - 1 do out[#out + 1] = track_summary(reaper.GetTrack(0, i)) end
    local m = reaper.GetMasterTrack(0)
    return {tracks = list(out), master = {volume_db = db_out(V(m, "D_VOL")), pan = V(m, "D_PAN"),
            mute = V(m, "B_MUTE") == 1, fx_count = reaper.TrackFX_GetCount(m)}}
end

H.track_get = function(p)
    local tr = get_track(p.track)
    local t = track_summary(tr)
    t.width = V(tr, "D_WIDTH")
    t.phase_inverted = V(tr, "B_PHASE") == 1
    t.input = math.tointeger(V(tr, "I_RECINPUT"))
    t.monitor = math.tointeger(V(tr, "I_RECMON"))
    t.record_mode = math.tointeger(V(tr, "I_RECMODE"))
    t.main_send = V(tr, "B_MAINSEND") == 1
    t.height = math.tointeger(V(tr, "I_TCPH"))
    t.sends = reaper.GetTrackNumSends(tr, 0)
    t.receives = reaper.GetTrackNumSends(tr, -1)
    t.hw_outputs = reaper.GetTrackNumSends(tr, 1)
    local fx = {}
    for i = 0, reaper.TrackFX_GetCount(tr) - 1 do
        local _, name = reaper.TrackFX_GetFXName(tr, i, "")
        fx[#fx + 1] = {index = i, name = name, enabled = reaper.TrackFX_GetEnabled(tr, i)}
    end
    t.fx = list(fx)
    local items = {}
    for i = 0, reaper.CountTrackMediaItems(tr) - 1 do
        local it = reaper.GetTrackMediaItem(tr, i)
        local take = reaper.GetActiveTake(it)
        items[#items + 1] = {index = item_index(it),
            position = reaper.GetMediaItemInfo_Value(it, "D_POSITION"),
            length = reaper.GetMediaItemInfo_Value(it, "D_LENGTH"),
            name = take and reaper.GetTakeName(take) or "",
            midi = take ~= nil and reaper.TakeIsMIDI(take)}
    end
    t.items = list(items)
    local env = {}
    for i = 0, reaper.CountTrackEnvelopes(tr) - 1 do
        local _, name = reaper.GetEnvelopeName(reaper.GetTrackEnvelope(tr, i))
        env[#env + 1] = name
    end
    t.envelopes = list(env)
    return t
end

-- apply optional properties; shared by create and set
local function apply_props(tr, p)
    if p.name ~= nil then reaper.GetSetMediaTrackInfo_String(tr, "P_NAME", p.name, true) end
    if p.volume_db ~= nil then reaper.SetMediaTrackInfo_Value(tr, "D_VOL", db_to_gain(p.volume_db)) end
    if p.pan ~= nil then
        if p.pan < -1 or p.pan > 1 then fail("pan must be -1..1") end
        reaper.SetMediaTrackInfo_Value(tr, "D_PAN", p.pan)
    end
    if p.width ~= nil then reaper.SetMediaTrackInfo_Value(tr, "D_WIDTH", p.width) end
    if p.mute ~= nil then reaper.SetMediaTrackInfo_Value(tr, "B_MUTE", p.mute and 1 or 0) end
    if p.solo ~= nil then reaper.SetMediaTrackInfo_Value(tr, "I_SOLO", p.solo and 2 or 0) end
    -- auto_arm=false must apply before arming, auto_arm=true after (dis)arming
    if p.auto_arm == false then reaper.SetMediaTrackInfo_Value(tr, "B_AUTO_RECARM", 0) end
    if p.arm ~= nil then
        -- with "automatic record-arm when selected" the arm state follows selection and a
        -- direct arm is silently overridden
        if V(tr, "B_AUTO_RECARM") == 1 then
            fail("track has automatic record-arm (follows selection): select it with track_select, or pass auto_arm=false")
        end
        reaper.SetMediaTrackInfo_Value(tr, "I_RECARM", p.arm and 1 or 0)
    end
    if p.auto_arm == true then reaper.SetMediaTrackInfo_Value(tr, "B_AUTO_RECARM", 1) end
    if p.phase_inverted ~= nil then reaper.SetMediaTrackInfo_Value(tr, "B_PHASE", p.phase_inverted and 1 or 0) end
    if p.color ~= nil then reaper.SetMediaTrackInfo_Value(tr, "I_CUSTOMCOLOR", color_to_native(p.color)) end
    if p.clear_color then reaper.SetMediaTrackInfo_Value(tr, "I_CUSTOMCOLOR", 0) end
    if p.input ~= nil then reaper.SetMediaTrackInfo_Value(tr, "I_RECINPUT", p.input) end
    if p.monitor ~= nil then reaper.SetMediaTrackInfo_Value(tr, "I_RECMON", p.monitor) end
    if p.record_mode ~= nil then reaper.SetMediaTrackInfo_Value(tr, "I_RECMODE", p.record_mode) end
    if p.folder_depth ~= nil then reaper.SetMediaTrackInfo_Value(tr, "I_FOLDERDEPTH", p.folder_depth) end
    if p.main_send ~= nil then reaper.SetMediaTrackInfo_Value(tr, "B_MAINSEND", p.main_send and 1 or 0) end
    if p.selected ~= nil then reaper.SetMediaTrackInfo_Value(tr, "I_SELECTED", p.selected and 1 or 0) end
    if p.height ~= nil then
        reaper.SetMediaTrackInfo_Value(tr, "I_HEIGHTOVERRIDE", p.height)
        reaper.TrackList_AdjustWindows(false)
    end
end

H.track_create = function(p)
    local n = reaper.CountTracks(0)
    local idx = opt(p.index, n)
    if idx < 0 or idx > n then fail("index must be 0..%d", n) end
    return undoable("create track", function()
        reaper.InsertTrackAtIndex(idx, true)
        local tr = reaper.GetTrack(0, idx)
        apply_props(tr, p)
        return track_summary(tr)
    end)
end

H.track_set = function(p)
    local tr = get_track(p.track)
    return undoable("set track", function()
        apply_props(tr, p)
        return track_summary(tr)
    end)
end

H.track_delete = function(p)
    local tr = get_track(p.track)
    if tr == reaper.GetMasterTrack(0) then fail("the master track can't be deleted") end
    local name = track_name(tr)
    undoable("delete track", function() reaper.DeleteTrack(tr) end)
    return {deleted = name, track_count = reaper.CountTracks(0)}
end

-- remember/restore track selection around operations that need it
local function save_track_selection()
    local sel = {}
    for i = 0, reaper.CountSelectedTracks(0) - 1 do sel[#sel + 1] = reaper.GetSelectedTrack(0, i) end
    return sel
end
local function restore_track_selection(sel)
    for i = 0, reaper.CountTracks(0) - 1 do reaper.SetTrackSelected(reaper.GetTrack(0, i), false) end
    for _, tr in ipairs(sel) do
        if reaper.ValidatePtr2(0, tr, "MediaTrack*") then reaper.SetTrackSelected(tr, true) end
    end
end

H.track_move = function(p)
    local tr = get_track(p.track)
    local n = reaper.CountTracks(0)
    local to = p.to_index
    if type(to) ~= "number" or to < 0 or to >= n then fail("to_index must be 0..%d", n - 1) end
    local from = track_index(tr)
    return undoable("move track", function()
        local sel = save_track_selection()
        reaper.SetOnlyTrackSelected(tr)
        -- ReorderSelectedTracks inserts before the given index (counted before removal)
        local before = to > from and to + 1 or to
        reaper.ReorderSelectedTracks(before, 0)
        restore_track_selection(sel)
        return track_summary(tr)
    end)
end

H.track_duplicate = function(p)
    local tr = get_track(p.track)
    if tr == reaper.GetMasterTrack(0) then fail("the master track can't be duplicated") end
    return undoable("duplicate track", function()
        local sel = save_track_selection()
        reaper.SetOnlyTrackSelected(tr)
        reaper.Main_OnCommand(40062, 0)            -- Track: Duplicate tracks
        local copy = reaper.GetTrack(0, track_index(tr) + 1)
        restore_track_selection(sel)
        return track_summary(copy)
    end)
end

H.track_select = function(p)
    local tracks = p.tracks or json_array({}, 0)
    if not p.add then
        for i = 0, reaper.CountTracks(0) - 1 do reaper.SetTrackSelected(reaper.GetTrack(0, i), false) end
    end
    for i = 1, array_len(tracks) do reaper.SetTrackSelected(get_track(tracks[i]), true) end
    local sel = {}
    for i = 0, reaper.CountSelectedTracks(0) - 1 do sel[#sel + 1] = track_index(reaper.GetSelectedTrack(0, i)) end
    return {selected = list(sel)}
end

H.track_chunk_get = function(p)
    local _, chunk = reaper.GetTrackStateChunk(get_track(p.track), "", false)
    return {chunk = chunk}
end

H.track_chunk_set = function(p)
    local tr = get_track(p.track)
    if type(p.chunk) ~= "string" or not p.chunk:match("^<TRACK") then fail("chunk must start with <TRACK") end
    local ok = undoable("set track chunk", function() return reaper.SetTrackStateChunk(tr, p.chunk, false) end)
    if not ok then fail("REAPER rejected the chunk") end
    return {ok = true}
end

end
-- >>> 30_item.lua
do
-- Media items and takes

local function IV(it, k) return reaper.GetMediaItemInfo_Value(it, k) end
local function TV(tk, k) return reaper.GetMediaItemTakeInfo_Value(tk, k) end

local function item_summary(it)
    local take = reaper.GetActiveTake(it)
    local pos, len = IV(it, "D_POSITION"), IV(it, "D_LENGTH")
    return {
        index = item_index(it),
        guid = guid_of_item(it),
        track = track_index(reaper.GetMediaItem_Track(it)),
        position = pos, length = len, ["end"] = pos + len,
        name = take and reaper.GetTakeName(take) or "",
        midi = take ~= nil and reaper.TakeIsMIDI(take),
        mute = IV(it, "B_MUTE") == 1,
        locked = IV(it, "C_LOCK") & 1 == 1,
        selected = IV(it, "B_UISEL") == 1,
        color = color_from_native(math.tointeger(IV(it, "I_CUSTOMCOLOR"))),
        takes = reaper.CountTakes(it),
        active_take = take and math.tointeger(TV(take, "IP_TAKENUMBER")) or NULL,
    }
end

local function take_info(tk)
    local src = reaper.GetMediaItemTake_Source(tk)
    local file = src and reaper.GetMediaSourceFileName(src, "") or ""
    local t = {
        index = math.tointeger(TV(tk, "IP_TAKENUMBER")),
        name = reaper.GetTakeName(tk),
        guid = select(2, reaper.GetSetMediaItemTakeInfo_String(tk, "GUID", "", false)),
        midi = reaper.TakeIsMIDI(tk),
        source = file ~= "" and file or NULL,
        source_type = src and reaper.GetMediaSourceType(src, "") or NULL,
        volume_db = db_out(math.abs(TV(tk, "D_VOL"))),
        polarity_inverted = TV(tk, "D_VOL") < 0,
        pan = TV(tk, "D_PAN"),
        pitch = TV(tk, "D_PITCH"),
        playrate = TV(tk, "D_PLAYRATE"),
        preserve_pitch = TV(tk, "B_PPITCH") == 1,
        start_offset = TV(tk, "D_STARTOFFS"),
        color = color_from_native(math.tointeger(TV(tk, "I_CUSTOMCOLOR"))),
    }
    if t.midi then
        local _, notes, ccs, sysex = reaper.MIDI_CountEvts(tk)
        t.notes, t.ccs, t.sysex = notes, ccs, sysex
    end
    return t
end

H.item_list = function(p)
    local tr = p.track ~= nil and get_track(p.track) or nil
    local out = {}
    for i = 0, reaper.CountMediaItems(0) - 1 do
        local it = reaper.GetMediaItem(0, i)
        local pos = IV(it, "D_POSITION")
        local ok = (not tr or reaper.GetMediaItem_Track(it) == tr)
            and (p.start == nil or pos + IV(it, "D_LENGTH") > p.start)
            and (p["end"] == nil or pos < p["end"])
            and (not p.selected_only or IV(it, "B_UISEL") == 1)
        if ok then out[#out + 1] = item_summary(it) end
    end
    return {items = list(out)}
end

H.item_get = function(p)
    local it = get_item(p.item)
    local t = item_summary(it)
    t.volume_db = db_out(IV(it, "D_VOL"))
    t.fade_in, t.fade_out = IV(it, "D_FADEINLEN"), IV(it, "D_FADEOUTLEN")
    t.fade_in_shape, t.fade_out_shape = math.tointeger(IV(it, "C_FADEINSHAPE")), math.tointeger(IV(it, "C_FADEOUTSHAPE"))
    t.snap_offset = IV(it, "D_SNAPOFFSET")
    t.loop_source = IV(it, "B_LOOPSRC") == 1
    local _, notes = reaper.GetSetMediaItemInfo_String(it, "P_NOTES", "", false)
    t.notes = notes
    local takes = {}
    for i = 0, reaper.CountTakes(it) - 1 do
        local tk = reaper.GetTake(it, i)
        if tk then takes[#takes + 1] = take_info(tk) end
    end
    t.take_list = list(takes)
    return t
end

local function apply_item_props(it, p)
    if p.track ~= nil then
        local tr = get_track(p.track)
        if tr == reaper.GetMasterTrack(0) then fail("items can't be on the master track") end
        if reaper.GetMediaItem_Track(it) ~= tr and not reaper.MoveMediaItemToTrack(it, tr) then
            fail("could not move the item to that track")
        end
    end
    if p.position ~= nil then reaper.SetMediaItemInfo_Value(it, "D_POSITION", p.position) end
    if p.length ~= nil then
        if p.length <= 0 then fail("length must be > 0") end
        reaper.SetMediaItemInfo_Value(it, "D_LENGTH", p.length)
    end
    if p.mute ~= nil then reaper.SetMediaItemInfo_Value(it, "B_MUTE", p.mute and 1 or 0) end
    if p.locked ~= nil then reaper.SetMediaItemInfo_Value(it, "C_LOCK", p.locked and 1 or 0) end
    if p.selected ~= nil then reaper.SetMediaItemInfo_Value(it, "B_UISEL", p.selected and 1 or 0) end
    if p.color ~= nil then reaper.SetMediaItemInfo_Value(it, "I_CUSTOMCOLOR", color_to_native(p.color)) end
    if p.clear_color then reaper.SetMediaItemInfo_Value(it, "I_CUSTOMCOLOR", 0) end
    if p.volume_db ~= nil then reaper.SetMediaItemInfo_Value(it, "D_VOL", db_to_gain(p.volume_db)) end
    if p.fade_in ~= nil then reaper.SetMediaItemInfo_Value(it, "D_FADEINLEN", p.fade_in) end
    if p.fade_out ~= nil then reaper.SetMediaItemInfo_Value(it, "D_FADEOUTLEN", p.fade_out) end
    if p.fade_in_shape ~= nil then reaper.SetMediaItemInfo_Value(it, "C_FADEINSHAPE", p.fade_in_shape) end
    if p.fade_out_shape ~= nil then reaper.SetMediaItemInfo_Value(it, "C_FADEOUTSHAPE", p.fade_out_shape) end
    if p.snap_offset ~= nil then reaper.SetMediaItemInfo_Value(it, "D_SNAPOFFSET", p.snap_offset) end
    if p.loop_source ~= nil then reaper.SetMediaItemInfo_Value(it, "B_LOOPSRC", p.loop_source and 1 or 0) end
    if p.notes ~= nil then reaper.GetSetMediaItemInfo_String(it, "P_NOTES", p.notes, true) end
    if p.active_take ~= nil then
        local tk = reaper.GetTake(it, p.active_take)
        if not tk then fail("item has no take %d", p.active_take) end
        reaper.SetActiveTake(tk)
    end
    if p.name ~= nil then
        local tk = reaper.GetActiveTake(it)
        if not tk then fail("item has no take to name") end
        reaper.GetSetMediaItemTakeInfo_String(tk, "P_NAME", p.name, true)
    end
    reaper.UpdateItemInProject(it)
end

H.item_set = function(p)
    local it = get_item(p.item)
    return undoable("set item", function() apply_item_props(it, p); return item_summary(it) end)
end

local function item_track(ref)
    local tr = get_track(ref)
    if tr == reaper.GetMasterTrack(0) then fail("items can't be on the master track") end
    return tr
end

H.item_create_midi = function(p)
    local tr = item_track(p.track)
    local s = check_time(p.start, "start")
    local e = p["end"] or (p.length and s + p.length)
    if not e or e <= s then fail("give end (> start) or length (> 0)") end
    return undoable("create MIDI item", function()
        local it = reaper.CreateNewMIDIItemInProj(tr, s, e, false)
        if not it then fail("REAPER could not create the MIDI item") end
        if p.name then reaper.GetSetMediaItemTakeInfo_String(reaper.GetActiveTake(it), "P_NAME", p.name, true) end
        return item_summary(it)
    end)
end

H.item_insert_media = function(p)
    local tr = item_track(p.track)
    local pos = check_time(opt(p.position, 0), "position")
    if type(p.path) ~= "string" or p.path == "" then fail("path is required") end
    if not reaper.file_exists(p.path) then fail("file not found on the REAPER machine: %s", p.path) end
    return undoable("insert media", function()
        local src = reaper.PCM_Source_CreateFromFile(p.path)
        if not src then fail("REAPER can't read %s", p.path) end
        local len, is_qn = reaper.GetMediaSourceLength(src)
        if is_qn then len = reaper.TimeMap_QNToTime(len) end
        local it = reaper.AddMediaItemToTrack(tr)
        local tk = reaper.AddTakeToMediaItem(it)
        reaper.SetMediaItemTake_Source(tk, src)
        reaper.GetSetMediaItemTakeInfo_String(tk, "P_NAME", p.path:match("([^/\\]+)$"), true)
        reaper.SetMediaItemInfo_Value(it, "D_POSITION", pos)
        reaper.SetMediaItemInfo_Value(it, "D_LENGTH", p.length or len)
        reaper.UpdateItemInProject(it)
        reaper.Main_OnCommand(40047, 0)     -- Peaks: Build any missing peaks
        return item_summary(it)
    end)
end

H.item_delete = function(p)
    local it = get_item(p.item)
    undoable("delete item", function() reaper.DeleteTrackMediaItem(reaper.GetMediaItem_Track(it), it) end)
    return {item_count = reaper.CountMediaItems(0)}
end

H.item_split = function(p)
    local it = get_item(p.item)
    local t = check_time(p.position, "position")
    local pos, len = IV(it, "D_POSITION"), IV(it, "D_LENGTH")
    if t <= pos or t >= pos + len then fail("position must be inside the item (%.3f-%.3f)", pos, pos + len) end
    return undoable("split item", function()
        local right = reaper.SplitMediaItem(it, t)
        if not right then fail("REAPER could not split the item") end
        return {left = item_summary(it), right = item_summary(right)}
    end)
end

-- selection helpers for the few operations that only exist as actions
local function save_item_selection()
    local sel = {}
    for i = 0, reaper.CountSelectedMediaItems(0) - 1 do sel[#sel + 1] = reaper.GetSelectedMediaItem(0, i) end
    return sel
end
local function select_only_items(items)
    reaper.SelectAllMediaItems(0, false)
    for _, it in ipairs(items) do reaper.SetMediaItemSelected(it, true) end
end
local function restore_item_selection(sel)
    reaper.SelectAllMediaItems(0, false)
    for _, it in ipairs(sel) do
        if reaper.ValidatePtr2(0, it, "MediaItem*") then reaper.SetMediaItemSelected(it, true) end
    end
end

H.item_duplicate = function(p)
    local it = get_item(p.item)
    return undoable("duplicate item", function()
        local sel = save_item_selection()
        select_only_items({it})
        reaper.Main_OnCommand(41295, 0)    -- Item: Duplicate items (copy placed right after)
        local copy = reaper.GetSelectedMediaItem(0, 0)
        if not copy or copy == it then restore_item_selection(sel); fail("REAPER did not duplicate the item") end
        apply_item_props(copy, {position = p.position, track = p.track})
        restore_item_selection(sel)
        return item_summary(copy)
    end)
end

H.item_glue = function(p)
    local items = {}
    for i = 1, array_len(p.items or json_array({}, 0)) do items[#items + 1] = get_item(p.items[i]) end
    if #items == 0 then fail("items is required") end
    return undoable("glue items", function()
        local sel = save_item_selection()
        select_only_items(items)
        reaper.Main_OnCommand(41588, 0)    -- Item: Glue items
        local out = {}
        for i = 0, reaper.CountSelectedMediaItems(0) - 1 do out[#out + 1] = item_summary(reaper.GetSelectedMediaItem(0, i)) end
        restore_item_selection(sel)
        return {items = list(out)}
    end)
end

H.item_select = function(p)
    if not p.add then reaper.SelectAllMediaItems(0, false) end
    for i = 1, array_len(p.items or json_array({}, 0)) do reaper.SetMediaItemSelected(get_item(p.items[i]), true) end
    reaper.UpdateArrange()
    local sel = {}
    for i = 0, reaper.CountSelectedMediaItems(0) - 1 do sel[#sel + 1] = item_index(reaper.GetSelectedMediaItem(0, i)) end
    return {selected = list(sel)}
end

H.item_chunk_get = function(p)
    local _, chunk = reaper.GetItemStateChunk(get_item(p.item), "", false)
    return {chunk = chunk}
end

H.item_chunk_set = function(p)
    local it = get_item(p.item)
    if type(p.chunk) ~= "string" or not p.chunk:match("^<ITEM") then fail("chunk must start with <ITEM") end
    local ok = undoable("set item chunk", function() return reaper.SetItemStateChunk(it, p.chunk, false) end)
    if not ok then fail("REAPER rejected the chunk") end
    return item_summary(it)
end

-- takes

H.take_set = function(p)
    local it = get_item(p.item)
    local tk = get_take(it, p.take)
    return undoable("set take", function()
        if p.name ~= nil then reaper.GetSetMediaItemTakeInfo_String(tk, "P_NAME", p.name, true) end
        if p.volume_db ~= nil then
            local sign = TV(tk, "D_VOL") < 0 and -1 or 1
            reaper.SetMediaItemTakeInfo_Value(tk, "D_VOL", sign * db_to_gain(p.volume_db))
        end
        if p.pan ~= nil then reaper.SetMediaItemTakeInfo_Value(tk, "D_PAN", p.pan) end
        if p.pitch ~= nil then reaper.SetMediaItemTakeInfo_Value(tk, "D_PITCH", p.pitch) end
        if p.playrate ~= nil then
            if p.playrate <= 0 then fail("playrate must be > 0") end
            reaper.SetMediaItemTakeInfo_Value(tk, "D_PLAYRATE", p.playrate)
        end
        if p.preserve_pitch ~= nil then reaper.SetMediaItemTakeInfo_Value(tk, "B_PPITCH", p.preserve_pitch and 1 or 0) end
        if p.start_offset ~= nil then reaper.SetMediaItemTakeInfo_Value(tk, "D_STARTOFFS", p.start_offset) end
        if p.color ~= nil then reaper.SetMediaItemTakeInfo_Value(tk, "I_CUSTOMCOLOR", color_to_native(p.color)) end
        if p.active then reaper.SetActiveTake(tk) end
        reaper.UpdateItemInProject(it)
        return take_info(tk)
    end)
end

H.take_add = function(p)
    local it = get_item(p.item)
    if p.path and not reaper.file_exists(p.path) then fail("file not found on the REAPER machine: %s", p.path) end
    return undoable("add take", function()
        local tk = reaper.AddTakeToMediaItem(it)
        if p.path then
            local src = reaper.PCM_Source_CreateFromFile(p.path)
            if not src then fail("REAPER can't read %s", p.path) end
            reaper.SetMediaItemTake_Source(tk, src)
            reaper.GetSetMediaItemTakeInfo_String(tk, "P_NAME", p.path:match("([^/\\]+)$"), true)
        end
        if p.name then reaper.GetSetMediaItemTakeInfo_String(tk, "P_NAME", p.name, true) end
        if opt(p.active, true) then reaper.SetActiveTake(tk) end
        reaper.UpdateItemInProject(it)
        return take_info(tk)
    end)
end

H.take_delete = function(p)
    local it = get_item(p.item)
    local tk = get_take(it, p.take)
    if reaper.CountTakes(it) < 2 then fail("item has only one take - delete the item instead") end
    return undoable("delete take", function()
        local sel = save_item_selection()
        local prev_active = reaper.GetActiveTake(it)
        select_only_items({it})
        reaper.SetActiveTake(tk)
        reaper.Main_OnCommand(40129, 0)    -- Take: Delete active take from items
        if prev_active ~= tk and reaper.ValidatePtr2(0, prev_active, "MediaItem_Take*") then
            reaper.SetActiveTake(prev_active)
        end
        restore_item_selection(sel)
        return item_summary(it)
    end)
end

end
-- >>> 40_midi.lua
do
-- MIDI editing. Positions use `unit`: "seconds" (project time), "qn" (project quarter notes,
-- follows the tempo map) or "ppq" (take ticks).

local function to_ppq(take, v, unit)
    if unit == "ppq" then return v
    elseif unit == "seconds" then return reaper.MIDI_GetPPQPosFromProjTime(take, v)
    elseif unit == "qn" then return reaper.MIDI_GetPPQPosFromProjQN(take, v)
    end
    fail("unit must be seconds, qn or ppq")
end

local function from_ppq(take, ppq, unit)
    if unit == "ppq" then return ppq
    elseif unit == "seconds" then return reaper.MIDI_GetProjTimeFromPPQPos(take, ppq)
    else return reaper.MIDI_GetProjQNFromPPQPos(take, ppq) end
end

local function to_hex(s) return (s:gsub(".", function(c) return string.format("%02x", c:byte()) end)) end
local function from_hex(h)
    if type(h) ~= "string" or h:find("[^%x]") or #h % 2 == 1 then fail("bad hex MIDI message: %s", tostring(h)) end
    return (h:gsub("%x%x", function(x) return string.char(tonumber(x, 16)) end))
end

local NOTE_FIELDS = {"index", "pitch", "velocity", "channel", "start_qn", "end_qn", "start_sec", "end_sec",
                     "start_ppq", "end_ppq", "selected", "muted"}
local CC_FIELDS = {"index", "type", "cc", "value", "channel", "qn", "sec", "ppq", "selected", "muted"}
local EVENT_FIELDS = {"ppq", "flags", "hex", "sec", "qn"}

local CC_TYPES = {[0xB0] = "cc", [0xE0] = "pitchbend", [0xC0] = "program", [0xD0] = "channel_pressure",
                  [0xA0] = "poly_aftertouch"}
local CC_STATUS = {cc = 0xB0, pitchbend = 0xE0, program = 0xC0, channel_pressure = 0xD0, poly_aftertouch = 0xA0}

local function note_row(take, i)
    local _, sel, mute, sp, ep, ch, pitch, vel = reaper.MIDI_GetNote(take, i)
    return json_array({i, pitch, vel, ch,
        reaper.MIDI_GetProjQNFromPPQPos(take, sp), reaper.MIDI_GetProjQNFromPPQPos(take, ep),
        reaper.MIDI_GetProjTimeFromPPQPos(take, sp), reaper.MIDI_GetProjTimeFromPPQPos(take, ep),
        sp, ep, sel, mute}, 12)
end

local function cc_row(take, i)
    local _, sel, mute, ppq, chanmsg, ch, m2, m3 = reaper.MIDI_GetCC(take, i)
    local typ = CC_TYPES[chanmsg] or string.format("0x%02x", chanmsg)
    local num, val = m2, m3
    if chanmsg == 0xE0 then num, val = NULL, (m3 << 7 | m2) - 8192
    elseif chanmsg == 0xC0 or chanmsg == 0xD0 then num, val = NULL, m2 end
    return json_array({i, typ, num, val, ch, reaper.MIDI_GetProjQNFromPPQPos(take, ppq),
        reaper.MIDI_GetProjTimeFromPPQPos(take, ppq), ppq, sel, mute}, 10)
end

H.midi_get = function(p)
    local item, take = get_midi_take(p)
    local _, nn, nc, nt = reaper.MIDI_CountEvts(take)
    local qn0 = reaper.MIDI_GetProjQNFromPPQPos(take, 0)
    local r = {
        item = item_index(item), take = math.tointeger(reaper.GetMediaItemTakeInfo_Value(take, "IP_TAKENUMBER")),
        counts = {notes = nn, ccs = nc, sysex_text = nt},
        ppq_per_qn = round(reaper.MIDI_GetPPQPosFromProjQN(take, qn0 + 1) - reaper.MIDI_GetPPQPosFromProjQN(take, qn0)),
        item_position = reaper.GetMediaItemInfo_Value(item, "D_POSITION"),
        item_length = reaper.GetMediaItemInfo_Value(item, "D_LENGTH"),
    }
    local _, chunk = reaper.GetItemStateChunk(item, "", false)
    r.follows_project_tempo = (chunk:match("IGNTEMPO (%d)") or "0") == "0"
    if opt(p.notes, true) then
        local rows = {}
        for i = 0, nn - 1 do rows[i + 1] = note_row(take, i) end
        r.note_fields, r.notes = list(NOTE_FIELDS), json_array(rows, nn)
    end
    if opt(p.ccs, true) then
        local rows = {}
        for i = 0, nc - 1 do rows[i + 1] = cc_row(take, i) end
        r.cc_fields, r.ccs = list(CC_FIELDS), json_array(rows, nc)
    end
    if p.events then
        local ok, buf = reaper.MIDI_GetAllEvts(take, "")
        if not ok then fail("MIDI_GetAllEvts failed") end
        local rows, n, pos, ppq = {}, 0, 1, 0
        while pos + 8 <= #buf do
            local off, flags, len
            off, flags, len, pos = string.unpack("<i4Bi4", buf, pos)
            local msg = buf:sub(pos, pos + len - 1)
            pos = pos + len
            ppq = ppq + off
            n = n + 1
            rows[n] = json_array({ppq, flags, to_hex(msg), reaper.MIDI_GetProjTimeFromPPQPos(take, ppq),
                                  reaper.MIDI_GetProjQNFromPPQPos(take, ppq)}, 5)
        end
        r.event_fields, r.events = list(EVENT_FIELDS), json_array(rows, n)
    end
    return r
end

-- Replace ALL events: events = [[pos, flags, hexmsg], ...] in `unit` (default ppq).
H.midi_set = function(p)
    local item, take = get_midi_take(p)
    local unit = opt(p.unit, "ppq")
    local evs = p.events or json_array({}, 0)
    local list_ = {}
    for i = 1, array_len(evs) do
        local e = evs[i]
        list_[i] = {ppq = round(to_ppq(take, e[1], unit)), flags = e[2] or 0, msg = from_hex(e[3]), idx = i}
    end
    table.sort(list_, function(a, b) if a.ppq ~= b.ppq then return a.ppq < b.ppq end return a.idx < b.idx end)
    local parts, last = {}, 0
    for i, e in ipairs(list_) do
        parts[i] = string.pack("<i4Bi4", e.ppq - last, e.flags, #e.msg) .. e.msg
        last = e.ppq
    end
    return undoable("replace MIDI", function()
        if not reaper.MIDI_SetAllEvts(take, table.concat(parts)) then fail("MIDI_SetAllEvts failed") end
        reaper.MIDI_Sort(take)
        if p.fit_item and #list_ > 0 then
            local pos = reaper.GetMediaItemInfo_Value(item, "D_POSITION")
            reaper.MIDI_SetItemExtents(item, reaper.TimeMap2_timeToQN(0, pos),
                reaper.MIDI_GetProjQNFromPPQPos(take, list_[#list_].ppq))
        end
        local _, nn, nc = reaper.MIDI_CountEvts(take)
        return {events = #list_, notes = nn, ccs = nc, item_length = reaper.GetMediaItemInfo_Value(item, "D_LENGTH")}
    end)
end

local function check_pitch(v, what)
    if type(v) ~= "number" or v < 0 or v > 127 or v ~= math.floor(v) then fail("%s must be an integer 0-127", what) end
    return math.tointeger(v)
end

H.midi_insert_notes = function(p)
    local item, take = get_midi_take(p)
    local unit = opt(p.unit, "qn")
    local notes = p.notes or json_array({}, 0)
    local n = array_len(notes)
    if n == 0 then fail("notes is required") end
    return undoable("insert notes", function()
        for i = 1, n do
            local q = notes[i]
            local s = to_ppq(take, q.start or fail("note %d: start is required", i), unit)
            local e
            if q["end"] ~= nil then e = to_ppq(take, q["end"], unit)
            elseif q.length ~= nil then
                if unit == "ppq" then e = s + q.length else e = to_ppq(take, q.start + q.length, unit) end
            else fail("note %d: give end or length", i) end
            if e <= s then fail("note %d: end must be after start", i) end
            reaper.MIDI_InsertNote(take, q.selected and true or false, q.muted and true or false, round(s), round(e),
                opt(q.channel, 0), check_pitch(q.pitch, "pitch"), check_pitch(opt(q.velocity, 96), "velocity"), true)
        end
        reaper.MIDI_Sort(take)
        local _, nn = reaper.MIDI_CountEvts(take)
        return {inserted = n, notes = nn}
    end)
end

-- note/cc filter: indices | pitch/cc range, time range (unit), channel, selected_only
local function matches(take, unit, f, idx, ppq, pitch, ch, sel)
    if f.indices then
        local hit = false
        for i = 1, array_len(f.indices) do if f.indices[i] == idx then hit = true break end end
        if not hit then return false end
    end
    if f.pitch_min and pitch < f.pitch_min then return false end
    if f.pitch_max and pitch > f.pitch_max then return false end
    if f.channel and ch ~= f.channel then return false end
    if f.selected_only and not sel then return false end
    if f.start and from_ppq(take, ppq, unit) < f.start - 1e-9 then return false end
    if f["end"] and from_ppq(take, ppq, unit) >= f["end"] - 1e-9 then return false end
    return true
end

local function selected_notes(take, p, unit)
    local _, nn = reaper.MIDI_CountEvts(take)
    local out = {}
    for i = 0, nn - 1 do
        local _, sel, mute, sp, ep, ch, pitch = reaper.MIDI_GetNote(take, i)
        if matches(take, unit, p, i, sp, pitch, ch, sel) then out[#out + 1] = i end
    end
    return out
end

H.midi_edit_notes = function(p)
    local item, take = get_midi_take(p)
    local unit = opt(p.unit, "qn")
    local edits = p.edits or json_array({}, 0)
    local n = array_len(edits)
    if n == 0 then fail("edits is required") end
    local _, nn = reaper.MIDI_CountEvts(take)
    return undoable("edit notes", function()
        for i = 1, n do
            local e = edits[i]
            if type(e.index) ~= "number" or e.index < 0 or e.index >= nn then fail("edit %d: no note index %s", i, tostring(e.index)) end
            local _, sel, mute, sp, ep, ch, pitch, vel = reaper.MIDI_GetNote(take, e.index)
            local ns = e.start ~= nil and round(to_ppq(take, e.start, unit)) or sp
            local ne = ep
            if e["end"] ~= nil then ne = round(to_ppq(take, e["end"], unit))
            elseif e.length ~= nil then
                ne = unit == "ppq" and ns + e.length or round(to_ppq(take, from_ppq(take, ns, unit) + e.length, unit))
            elseif e.start ~= nil then ne = ns + (ep - sp) end         -- moving keeps the length
            if ne <= ns then fail("edit %d: end must be after start", i) end
            reaper.MIDI_SetNote(take, e.index, opt(e.selected, sel), opt(e.muted, mute), ns, ne,
                opt(e.channel, ch), e.pitch and check_pitch(e.pitch, "pitch") or pitch,
                e.velocity and check_pitch(e.velocity, "velocity") or vel, true)
        end
        reaper.MIDI_Sort(take)
        return {edited = n}
    end)
end

H.midi_delete_notes = function(p)
    local item, take = get_midi_take(p)
    local idx = selected_notes(take, p, opt(p.unit, "qn"))
    return undoable("delete notes", function()
        for i = #idx, 1, -1 do reaper.MIDI_DeleteNote(take, idx[i]) end
        local _, nn = reaper.MIDI_CountEvts(take)
        return {deleted = #idx, notes = nn}
    end)
end

H.midi_insert_ccs = function(p)
    local item, take = get_midi_take(p)
    local unit = opt(p.unit, "qn")
    local ccs = p.ccs or json_array({}, 0)
    local n = array_len(ccs)
    if n == 0 then fail("ccs is required") end
    return undoable("insert CCs", function()
        for i = 1, n do
            local c = ccs[i]
            local typ = opt(c.type, "cc")
            local status = CC_STATUS[typ] or fail("cc %d: type must be cc, pitchbend, program, channel_pressure or poly_aftertouch", i)
            local m2, m3
            if typ == "pitchbend" then
                local v = round(c.value) + 8192
                if v < 0 or v > 16383 then fail("cc %d: pitchbend value must be -8192..8191", i) end
                m2, m3 = v & 0x7F, v >> 7
            elseif typ == "program" or typ == "channel_pressure" then
                m2, m3 = check_pitch(c.value, "value"), 0
            else
                m2, m3 = check_pitch(c.cc, "cc"), check_pitch(c.value, "value")
            end
            local pos = to_ppq(take, c.position or fail("cc %d: position is required", i), unit)
            reaper.MIDI_InsertCC(take, c.selected and true or false, c.muted and true or false, round(pos),
                status, opt(c.channel, 0), m2, m3)
        end
        reaper.MIDI_Sort(take)
        local _, _, nc = reaper.MIDI_CountEvts(take)
        return {inserted = n, ccs = nc}
    end)
end

H.midi_delete_ccs = function(p)
    local item, take = get_midi_take(p)
    local unit = opt(p.unit, "qn")
    local _, _, nc = reaper.MIDI_CountEvts(take)
    local idx = {}
    for i = 0, nc - 1 do
        local _, sel, mute, ppq, chanmsg, ch, m2 = reaper.MIDI_GetCC(take, i)
        local ok = matches(take, unit, {indices = p.indices, channel = p.channel, selected_only = p.selected_only,
                                        start = p.start, ["end"] = p["end"]}, i, ppq, 0, ch, sel)
        if ok and p.type and CC_TYPES[chanmsg] ~= p.type then ok = false end
        if ok and p.cc and (chanmsg ~= 0xB0 or m2 ~= p.cc) then ok = false end
        if ok then idx[#idx + 1] = i end
    end
    return undoable("delete CCs", function()
        for i = #idx, 1, -1 do reaper.MIDI_DeleteCC(take, idx[i]) end
        local _, _, left = reaper.MIDI_CountEvts(take)
        return {deleted = #idx, ccs = left}
    end)
end

-- Quantize note starts (and optionally ends) to a grid in quarter notes of the PROJECT tempo
-- map, so a tempo-synced performance quantizes to the played beats.
H.midi_quantize = function(p)
    local item, take = get_midi_take(p)
    local grid = p.grid or fail("grid is required (in quarter notes: 1 = quarter, 0.5 = eighth, 1/3 = eighth triplet)")
    if grid <= 0 then fail("grid must be > 0") end
    local strength = opt(p.strength, 1.0)
    if strength < 0 or strength > 1 then fail("strength must be 0..1") end
    local swing = opt(p.swing, 0)
    local idx = selected_notes(take, p, opt(p.unit, "qn"))
    local function snap(q)
        local k = math.floor(q / grid + 0.5)
        local target = k * grid
        if swing ~= 0 and k % 2 == 1 then target = target + swing * grid * 0.5 end
        return q + (target - q) * strength
    end
    return undoable("quantize notes", function()
        local moved = 0
        for _, i in ipairs(idx) do
            local _, sel, mute, sp, ep, ch, pitch, vel = reaper.MIDI_GetNote(take, i)
            local qs, qe = reaper.MIDI_GetProjQNFromPPQPos(take, sp), reaper.MIDI_GetProjQNFromPPQPos(take, ep)
            local ns = round(reaper.MIDI_GetPPQPosFromProjQN(take, snap(qs)))
            local ne
            if p.ends then ne = round(reaper.MIDI_GetPPQPosFromProjQN(take, snap(qe)))
            else ne = ns + (ep - sp) end
            if ne <= ns then ne = ns + math.max(1, ep - sp) end
            if ns ~= sp or ne ~= ep then moved = moved + 1 end
            reaper.MIDI_SetNote(take, i, sel, mute, ns, ne, ch, pitch, vel, true)
        end
        reaper.MIDI_Sort(take)
        return {notes = #idx, moved = moved}
    end)
end

H.midi_transpose = function(p)
    local item, take = get_midi_take(p)
    local st = p.semitones
    if type(st) ~= "number" or st ~= math.floor(st) then fail("semitones must be an integer") end
    local idx = selected_notes(take, p, opt(p.unit, "qn"))
    for _, i in ipairs(idx) do
        local _, _, _, _, _, _, pitch = reaper.MIDI_GetNote(take, i)
        if pitch + st < 0 or pitch + st > 127 then fail("note %d would leave the MIDI range (pitch %d)", i, pitch + st) end
    end
    return undoable("transpose notes", function()
        for _, i in ipairs(idx) do
            local _, sel, mute, sp, ep, ch, pitch, vel = reaper.MIDI_GetNote(take, i)
            reaper.MIDI_SetNote(take, i, sel, mute, sp, ep, ch, math.tointeger(pitch + st), vel, true)
        end
        reaper.MIDI_Sort(take)
        return {transposed = #idx}
    end)
end

end
-- >>> 50_fx.lua
do
-- FX on tracks (incl. input/record FX) and takes.
-- Target: {track} | {track, input_fx=true} | {item, take}

local function target(p)
    if p.item ~= nil then
        local item = get_item(p.item)
        local tk = get_take(item, p.take)
        return {kind = "take", obj = tk, item = item,
            count = function() return reaper.TakeFX_GetCount(tk) end, idx = function(i) return i end,
            api = function(name, ...) return reaper["TakeFX_" .. name](tk, ...) end}
    end
    local tr = get_track(p.track)
    if p.input_fx then
        return {kind = "input", obj = tr,
            count = function() return reaper.TrackFX_GetRecCount(tr) end,
            idx = function(i) return i | 0x1000000 end,
            api = function(name, ...) return reaper["TrackFX_" .. name](tr, ...) end}
    end
    return {kind = "track", obj = tr,
        count = function() return reaper.TrackFX_GetCount(tr) end, idx = function(i) return i end,
        api = function(name, ...) return reaper["TrackFX_" .. name](tr, ...) end}
end

local function fx_index(T, i)
    local n = T.count()
    if type(i) ~= "number" or i < 0 or i >= n then fail("no FX %s (chain has %d)", tostring(i), n) end
    return T.idx(i)
end

local function fx_info(T, i)
    local fi = T.idx(i)
    local _, name = T.api("GetFXName", fi, "")
    local _, preset = T.api("GetPreset", fi, "")
    local pidx, pcount = T.api("GetPresetIndex", fi)
    return {index = i, name = name, guid = T.api("GetFXGUID", fi),
            enabled = T.api("GetEnabled", fi), offline = T.api("GetOffline", fi),
            preset = preset ~= "" and preset or NULL, preset_index = pidx >= 0 and pidx or NULL,
            preset_count = pcount, params = T.api("GetNumParams", fi), open = T.api("GetOpen", fi)}
end

H.fx_list = function(p)
    local T = target(p)
    local out = {}
    for i = 0, T.count() - 1 do out[#out + 1] = fx_info(T, i) end
    return {fx = list(out)}
end

H.fx_installed = function(p)
    local f = p.filter and p.filter:lower()
    local out, i = {}, 0
    while true do
        local ok, name, ident = reaper.EnumInstalledFX(i)
        if not ok then break end
        if not f or name:lower():find(f, 1, true) then out[#out + 1] = {name = name, ident = ident} end
        i = i + 1
        if #out >= opt(p.limit, 200) then break end
    end
    return {plugins = list(out), total_scanned = i}
end

H.fx_add = function(p)
    local T = target(p)
    if type(p.name) ~= "string" or p.name == "" then fail("name is required (see fx_installed)") end
    local n = T.count()
    local pos = opt(p.position, n)
    if pos < 0 or pos > n then fail("position must be 0..%d", n) end
    return undoable("add FX", function()
        local idx
        if T.kind == "take" then idx = reaper.TakeFX_AddByName(T.obj, p.name, -1000 - pos)
        else idx = reaper.TrackFX_AddByName(T.obj, p.name, T.kind == "input", -1000 - pos) end
        if idx < 0 then fail("plugin not found: '%s' (see fx_installed)", p.name) end
        return fx_info(T, idx & 0xFFFFFF)
    end)
end

H.fx_delete = function(p)
    local T = target(p)
    local fi = fx_index(T, p.fx)
    undoable("delete FX", function() T.api("Delete", fi) end)
    return {fx_count = T.count()}
end

H.fx_move = function(p)
    local T = target(p)
    local fi = fx_index(T, p.fx)
    return undoable("move FX", function()
        if p.to_track ~= nil then
            if T.kind == "take" then fail("moving take FX to a track is not supported") end
            local dest = get_track(p.to_track)
            local di = opt(p.to_index, reaper.TrackFX_GetCount(dest))
            reaper.TrackFX_CopyToTrack(T.obj, fi, dest, di, true)
            return {moved_to_track = track_index(dest), index = di}
        end
        local n = T.count()
        local to = p.to_index
        if type(to) ~= "number" or to < 0 or to >= n then fail("to_index must be 0..%d", n - 1) end
        if T.kind == "take" then reaper.TakeFX_CopyToTake(T.obj, fi, T.obj, to, true)
        else reaper.TrackFX_CopyToTrack(T.obj, fi, T.obj, T.idx(to), true) end
        return fx_info(T, to)
    end)
end

H.fx_set = function(p)
    local T = target(p)
    local fi = fx_index(T, p.fx)
    return undoable("set FX", function()
        if p.enabled ~= nil then T.api("SetEnabled", fi, p.enabled) end
        if p.offline ~= nil then T.api("SetOffline", fi, p.offline) end
        if p.wet ~= nil then
            local wi = T.api("GetParamFromIdent", fi, ":wet")
            if wi < 0 then fail("this FX has no wet/dry control") end
            T.api("SetParamNormalized", fi, wi, p.wet)
        end
        return fx_info(T, p.fx)
    end)
end

local function param_record(T, fi, j)
    local _, pname = T.api("GetParamName", fi, j, "")
    local val, minv, maxv = T.api("GetParam", fi, j)
    local _, fmt = T.api("GetFormattedParamValue", fi, j, "")
    return {index = j, name = pname, value = val, min = minv, max = maxv,
            normalized = T.api("GetParamNormalized", fi, j), formatted = fmt}
end

H.fx_params = function(p)
    local T = target(p)
    local fi = fx_index(T, p.fx)
    local f = p.filter and p.filter:lower()
    local out = {}
    for j = 0, T.api("GetNumParams", fi) - 1 do
        local _, pname = T.api("GetParamName", fi, j, "")
        if not f or pname:lower():find(f, 1, true) then out[#out + 1] = param_record(T, fi, j) end
    end
    local _, name = T.api("GetFXName", fi, "")
    return {fx = p.fx, name = name, params = list(out)}
end

local function find_param(T, fi, ref)
    local n = T.api("GetNumParams", fi)
    if type(ref) == "number" then
        if ref < 0 or ref >= n then fail("no parameter %d (FX has %d)", ref, n) end
        return ref
    end
    local lref, partial = tostring(ref):lower(), {}
    for j = 0, n - 1 do
        local _, pname = T.api("GetParamName", fi, j, "")
        if pname == ref then return j end
        if pname:lower():find(lref, 1, true) then partial[#partial + 1] = j end
    end
    if #partial == 1 then return partial[1] end
    if #partial == 0 then fail("no parameter named '%s'", tostring(ref)) end
    fail("parameter name '%s' is ambiguous (%d matches) - use the index", tostring(ref), #partial)
end

H.fx_param_set = function(p)
    local T = target(p)
    local fi = fx_index(T, p.fx)
    local ps = p.params or json_array({}, 0)
    if array_len(ps) == 0 then fail("params is required") end
    return undoable("set FX parameters", function()
        local out = {}
        for i = 1, array_len(ps) do
            local q = ps[i]
            local j = find_param(T, fi, q.param)
            if q.normalized ~= nil then
                if q.normalized < 0 or q.normalized > 1 then fail("normalized must be 0..1") end
                T.api("SetParamNormalized", fi, j, q.normalized)
            elseif q.value ~= nil then T.api("SetParam", fi, j, q.value)
            else fail("param %s: give value or normalized", tostring(q.param)) end
            out[#out + 1] = param_record(T, fi, j)
        end
        return {params = list(out)}
    end)
end

H.fx_presets = function(p)
    local T = target(p)
    local fi = fx_index(T, p.fx)
    local _, preset = T.api("GetPreset", fi, "")
    local pidx, count = T.api("GetPresetIndex", fi)
    return {preset = preset ~= "" and preset or NULL, index = pidx >= 0 and pidx or NULL, count = count}
end

H.fx_preset_set = function(p)
    local T = target(p)
    local fi = fx_index(T, p.fx)
    return undoable("set FX preset", function()
        if p.name ~= nil then
            if not T.api("SetPreset", fi, p.name) then fail("preset '%s' not found", p.name) end
        elseif p.index ~= nil then
            if not T.api("SetPresetByIndex", fi, p.index) then fail("no preset %d", p.index) end
        elseif p.step ~= nil then
            T.api("NavigatePresets", fi, p.step)
        else fail("give name, index or step") end
        return H.fx_presets(p)
    end)
end

H.fx_show = function(p)
    local T = target(p)
    local fi = fx_index(T, p.fx)
    local modes = {floating = 3, chain = 1, close_floating = 2, close_chain = 0}
    local m = modes[opt(p.mode, "floating")] or fail("mode must be floating, chain, close_floating or close_chain")
    T.api("Show", fi, m)
    return {open = T.api("GetOpen", fi)}
end

end
-- >>> 60_envelope.lua
do
-- Envelopes: track envelopes by name, FX parameter envelopes, take envelopes.
-- Target: {track, name} | {track, fx, param} | {item, take, name}

local BUILTIN = {   -- track envelope name -> action that shows it (verified by name before running)
    ["Volume"] = {40406, "volume envelope"}, ["Pan"] = {40407, "pan envelope"},
    ["Volume (Pre-FX)"] = {40408, "pre-fx volume envelope"}, ["Mute"] = {40867, "mute envelope"},
    ["Width"] = {41870, "width envelope"}, ["Trim Volume"] = {42020, "trim volume envelope"},
}

local function env_target(p, create)
    if p.item ~= nil then
        local tk = get_take(get_item(p.item), p.take)
        local env = reaper.GetTakeEnvelopeByName(tk, p.name or fail("name is required (Volume, Pan, Mute, Pitch)"))
        if not env then fail("take has no '%s' envelope (show it in REAPER first)", p.name) end
        return env
    end
    local tr = get_track(p.track)
    if p.fx ~= nil then
        local param = p.param
        if type(param) ~= "number" then fail("param (index) is required for FX envelopes") end
        local env = reaper.GetFXEnvelope(tr, p.fx, param, create and true or false)
        if not env then fail("no envelope for FX %d parameter %d", p.fx, param) end
        return env
    end
    local name = p.name or fail("name is required (e.g. Volume, Pan, Width, Mute)")
    local env = reaper.GetTrackEnvelopeByName(tr, name)
    if not env and create then
        local b = BUILTIN[name] or fail("'%s' can't be created automatically (built-in: Volume, Pan, Width, Mute, Volume (Pre-FX), Trim Volume)", name)
        local sel = {}
        for i = 0, reaper.CountSelectedTracks(0) - 1 do sel[#sel + 1] = reaper.GetSelectedTrack(0, i) end
        reaper.SetOnlyTrackSelected(tr)
        RUN_CHECKED_ACTION(b[1], b[2])
        for i = 0, reaper.CountTracks(0) - 1 do reaper.SetTrackSelected(reaper.GetTrack(0, i), false) end
        for _, t in ipairs(sel) do reaper.SetTrackSelected(t, true) end
        env = reaper.GetTrackEnvelopeByName(tr, name)
    end
    if not env then fail("track has no '%s' envelope (create=true makes it)", name) end
    return env
end

local function env_flags(env)
    local _, chunk = reaper.GetEnvelopeStateChunk(env, "", false)
    return {active = (chunk:match("\nACT (%d)") or "1") == "1",
            visible = (chunk:match("\nVIS (%d)") or "0") == "1",
            armed = (chunk:match("\nARM (%d)") or "0") == "1"}
end

local function env_summary(env)
    local _, name = reaper.GetEnvelopeName(env)
    local f = env_flags(env)
    return {name = name, points = reaper.CountEnvelopePoints(env), active = f.active, visible = f.visible,
            armed = f.armed, scaling_mode = reaper.GetEnvelopeScalingMode(env)}
end

H.envelope_list = function(p)
    local out = {}
    if p.item ~= nil then
        local tk = get_take(get_item(p.item), p.take)
        for i = 0, reaper.CountTakeEnvelopes(tk) - 1 do out[#out + 1] = env_summary(reaper.GetTakeEnvelope(tk, i)) end
    else
        local tr = get_track(p.track)
        for i = 0, reaper.CountTrackEnvelopes(tr) - 1 do
            local env = reaper.GetTrackEnvelope(tr, i)
            local s = env_summary(env)
            local _, fx, param = reaper.Envelope_GetParentTrack(env)
            if fx and fx >= 0 then s.fx, s.param = fx, param end
            out[#out + 1] = s
        end
    end
    return {envelopes = list(out)}
end

-- volume-type envelopes store fader-scaled values; value_db converts
local function is_volume(env)
    local _, name = reaper.GetEnvelopeName(env)
    return name:match("^Volume") or name:match("^Trim Volume")
end
local function raw_to_db(env, v) return db_out(reaper.ScaleFromEnvelopeMode(reaper.GetEnvelopeScalingMode(env), v)) end
local function db_to_raw(env, db) return reaper.ScaleToEnvelopeMode(reaper.GetEnvelopeScalingMode(env), db_to_gain(db)) end

H.envelope_get = function(p)
    local env = env_target(p, false)
    local s = env_summary(env)
    local vol = is_volume(env)
    local pts = {}
    for i = 0, reaper.CountEnvelopePoints(env) - 1 do
        local _, t, v, shape, tension, sel = reaper.GetEnvelopePoint(env, i)
        if (p.start == nil or t >= p.start - 1e-9) and (p["end"] == nil or t <= p["end"] + 1e-9) then
            pts[#pts + 1] = {index = i, time = t, value = v, value_db = vol and raw_to_db(env, v) or NULL,
                             shape = shape, tension = tension, selected = sel}
        end
    end
    s.point_list = list(pts)
    return s
end

-- points: [{time, value | value_db, shape=0, tension=0}]; replace=true deletes existing points
-- between the first and last new point first
H.envelope_points_set = function(p)
    local env = env_target(p, opt(p.create, true))
    local pts = p.points or json_array({}, 0)
    local n = array_len(pts)
    if n == 0 then fail("points is required") end
    return undoable("set envelope points", function()
        local tmin, tmax = math.huge, -math.huge
        for i = 1, n do tmin = math.min(tmin, pts[i].time); tmax = math.max(tmax, pts[i].time) end
        if opt(p.replace, true) then reaper.DeleteEnvelopePointRange(env, tmin - 1e-9, tmax + 1e-9) end
        for i = 1, n do
            local q = pts[i]
            local v = q.value
            if q.value_db ~= nil then
                if not is_volume(env) then fail("value_db only applies to volume envelopes") end
                v = db_to_raw(env, q.value_db)
            end
            if v == nil then fail("point %d: give value or value_db", i) end
            reaper.InsertEnvelopePoint(env, q.time, v, opt(q.shape, 0), opt(q.tension, 0), false, true)
        end
        reaper.Envelope_SortPoints(env)
        return env_summary(env)
    end)
end

H.envelope_points_delete = function(p)
    local env = env_target(p, false)
    local s, e = opt(p.start, -1e9), opt(p["end"], 1e9)
    return undoable("delete envelope points", function()
        local before = reaper.CountEnvelopePoints(env)
        reaper.DeleteEnvelopePointRange(env, s - 1e-9, e + 1e-9)
        return {deleted = before - reaper.CountEnvelopePoints(env), points = reaper.CountEnvelopePoints(env)}
    end)
end

H.envelope_set = function(p)
    local env = env_target(p, opt(p.create, true))
    return undoable("set envelope", function()
        local _, chunk = reaper.GetEnvelopeStateChunk(env, "", false)
        if p.active ~= nil then chunk = chunk:gsub("\nACT %d", "\nACT " .. (p.active and 1 or 0), 1) end
        if p.visible ~= nil then chunk = chunk:gsub("\nVIS %d", "\nVIS " .. (p.visible and 1 or 0), 1) end
        if p.armed ~= nil then chunk = chunk:gsub("\nARM %d", "\nARM " .. (p.armed and 1 or 0), 1) end
        reaper.SetEnvelopeStateChunk(env, chunk, false)
        reaper.TrackList_AdjustWindows(false)
        return env_summary(env)
    end)
end

end
-- >>> 70_marker.lua
do
-- Markers and regions (identified by their displayed number + is_region)

local function all_markers()
    local out, i = {}, 0
    while true do
        local ret, isrgn, pos, rend, name, num, color = reaper.EnumProjectMarkers3(0, i)
        if ret == 0 then break end
        out[#out + 1] = {number = num, region = isrgn, position = pos, ["end"] = isrgn and rend or NULL,
                         name = name, color = color_from_native(color), enum_index = i}
        i = i + 1
    end
    return out
end

local function find_marker(num, region)
    for _, m in ipairs(all_markers()) do
        if m.number == num and m.region == (region and true or false) then return m end
    end
    fail("no %s number %s", region and "region" or "marker", tostring(num))
end

H.marker_list = function(p)
    local markers, regions = {}, {}
    for _, m in ipairs(all_markers()) do
        m.enum_index = nil
        if m.region then regions[#regions + 1] = m else markers[#markers + 1] = m end
    end
    return {markers = list(markers), regions = list(regions)}
end

H.marker_add = function(p)
    local pos = check_time(p.position, "position")
    local isrgn = p["end"] ~= nil
    if isrgn and p["end"] <= pos then fail("region end must be after position") end
    return undoable("add marker", function()
        local num = reaper.AddProjectMarker2(0, isrgn, pos, p["end"] or 0, p.name or "", opt(p.number, -1),
            p.color and color_to_native(p.color) or 0)
        if num < 0 then fail("REAPER could not add the marker") end
        return find_marker(num, isrgn)
    end)
end

H.marker_set = function(p)
    local m = find_marker(p.number, p.region)
    return undoable("edit marker", function()
        local pos = opt(p.position, m.position)
        local rend = m.region and opt(p["end"], m["end"]) or 0
        local name = opt(p.name, m.name)
        local color = m.color ~= NULL and color_to_native(m.color) or 0
        if p.color ~= nil then color = color_to_native(p.color) end
        if p.clear_color then color = 0 end
        -- flags &1: allow setting an empty name
        reaper.SetProjectMarker4(0, m.number, m.region, pos, rend, name, color, name == "" and 1 or 0)
        return find_marker(m.number, m.region)
    end)
end

H.marker_delete = function(p)
    find_marker(p.number, p.region)
    undoable("delete marker", function() reaper.DeleteProjectMarker(0, p.number, p.region and true or false) end)
    local _, nm, nr = reaper.CountProjectMarkers(0)
    return {markers = nm, regions = nr}
end

end
-- >>> 75_routing.lua
do
-- Sends, receives and hardware outputs.  category: "send" | "receive" | "hardware"

local CAT = {send = 0, receive = -1, hardware = 1}
local MODES = {[0] = "post_fader", [1] = "pre_fx", [3] = "post_fx"}
local MODE_IDS = {post_fader = 0, pre_fx = 1, post_fx = 3}

local function S(tr, cat, i, k) return reaper.GetTrackSendInfo_Value(tr, cat, i, k) end

local function send_info(tr, cat, i)
    local r = {index = i, volume_db = db_out(S(tr, cat, i, "D_VOL")), pan = S(tr, cat, i, "D_PAN"),
               mute = S(tr, cat, i, "B_MUTE") == 1, mode = MODES[math.tointeger(S(tr, cat, i, "I_SENDMODE"))] or "other",
               src_channel = math.tointeger(S(tr, cat, i, "I_SRCCHAN")),
               dst_channel = math.tointeger(S(tr, cat, i, "I_DSTCHAN")),
               midi_flags = math.tointeger(S(tr, cat, i, "I_MIDIFLAGS"))}
    if cat == 0 then r.dest_track = track_index(reaper.GetTrackSendInfo_Value(tr, 0, i, "P_DESTTRACK"))
    elseif cat == -1 then r.source_track = track_index(reaper.GetTrackSendInfo_Value(tr, -1, i, "P_SRCTRACK")) end
    return r
end

H.send_list = function(p)
    local tr = get_track(p.track)
    local out = {}
    for name, cat in pairs(CAT) do
        local rows = {}
        for i = 0, reaper.GetTrackNumSends(tr, cat) - 1 do rows[#rows + 1] = send_info(tr, cat, i) end
        out[name .. "s"] = list(rows)
    end
    return out
end

local function apply_send(tr, cat, i, p)
    if p.volume_db ~= nil then reaper.SetTrackSendInfo_Value(tr, cat, i, "D_VOL", db_to_gain(p.volume_db)) end
    if p.pan ~= nil then reaper.SetTrackSendInfo_Value(tr, cat, i, "D_PAN", p.pan) end
    if p.mute ~= nil then reaper.SetTrackSendInfo_Value(tr, cat, i, "B_MUTE", p.mute and 1 or 0) end
    if p.mode ~= nil then
        reaper.SetTrackSendInfo_Value(tr, cat, i, "I_SENDMODE", MODE_IDS[p.mode] or fail("mode must be post_fader, pre_fx or post_fx"))
    end
    if p.src_channel ~= nil then reaper.SetTrackSendInfo_Value(tr, cat, i, "I_SRCCHAN", p.src_channel) end
    if p.dst_channel ~= nil then reaper.SetTrackSendInfo_Value(tr, cat, i, "I_DSTCHAN", p.dst_channel) end
    if p.midi_flags ~= nil then reaper.SetTrackSendInfo_Value(tr, cat, i, "I_MIDIFLAGS", p.midi_flags) end
end

H.send_create = function(p)
    local src = get_track(p.track)
    local dest = p.dest_track ~= nil and get_track(p.dest_track) or nil
    if dest == src then fail("a track can't send to itself") end
    return undoable("create send", function()
        local i = reaper.CreateTrackSend(src, dest)
        if i < 0 then fail("REAPER could not create the send") end
        local cat = dest and 0 or 1
        apply_send(src, cat, i, p)
        local r = send_info(src, cat, i)
        r.category = dest and "send" or "hardware"
        return r
    end)
end

local function send_ref(p)
    local tr = get_track(p.track)
    local cat = CAT[opt(p.category, "send")] or fail("category must be send, receive or hardware")
    local n = reaper.GetTrackNumSends(tr, cat)
    if type(p.index) ~= "number" or p.index < 0 or p.index >= n then fail("no %s %s (track has %d)", opt(p.category, "send"), tostring(p.index), n) end
    return tr, cat
end

H.send_set = function(p)
    local tr, cat = send_ref(p)
    return undoable("set send", function() apply_send(tr, cat, p.index, p); return send_info(tr, cat, p.index) end)
end

H.send_delete = function(p)
    local tr, cat = send_ref(p)
    undoable("delete send", function() reaper.RemoveTrackSend(tr, cat, p.index) end)
    return {remaining = reaper.GetTrackNumSends(tr, cat)}
end

end
-- >>> 80_render.lua
do
-- Rendering and freezing

local BOUNDS = {project = 1, time_selection = 2, custom = 0, all_regions = 3, selected_items = 4}

H.render_project = function(p)
    if reaper.GetPlayState() & 4 ~= 0 then fail("can't render while recording") end
    local function gs(k, v, set) return select(2, reaper.GetSetProjectInfo_String(0, k, v or "", set or false)) end
    local function gn(k, v, set) return reaper.GetSetProjectInfo(0, k, v or 0, set or false) end
    -- remember the project's render settings and put them back afterwards
    local saved = {file = gs("RENDER_FILE"), pattern = gs("RENDER_PATTERN"), format = gs("RENDER_FORMAT"),
                   bounds = gn("RENDER_BOUNDSFLAG"), s = gn("RENDER_STARTPOS"), e = gn("RENDER_ENDPOS"),
                   srate = gn("RENDER_SRATE"), chans = gn("RENDER_CHANNELS"), tail = gn("RENDER_TAILFLAG"),
                   settings = gn("RENDER_SETTINGS")}
    local ok, res = pcall(function()
        if p.directory then gs("RENDER_FILE", p.directory, true) end
        if p.file_name then gs("RENDER_PATTERN", p.file_name, true) end
        if p.bounds then
            local b = BOUNDS[p.bounds] or fail("bounds must be project, time_selection, custom, all_regions or selected_items")
            gn("RENDER_BOUNDSFLAG", b, true)
            if p.bounds == "custom" then
                gn("RENDER_STARTPOS", check_time(p.start, "start"), true)
                gn("RENDER_ENDPOS", check_time(p["end"], "end"), true)
            end
        end
        if p.wav_bits then
            -- REAPER's WAV render config ("evaw" + bit depth), base64-encoded
            local cfg = ({[16] = "ZXZhdxAAAQ==", [24] = "ZXZhdxgAAQ==", [32] = "ZXZhdyAAAQ=="})[p.wav_bits]
            gs("RENDER_FORMAT", cfg or fail("wav_bits must be 16, 24 or 32"), true)
        end
        if p.sample_rate then gn("RENDER_SRATE", p.sample_rate, true) end
        if p.channels then gn("RENDER_CHANNELS", p.channels, true) end
        if p.tail_ms then gn("RENDER_TAILFLAG", 0xFF, true); gn("RENDER_TAILMS", p.tail_ms, true) end
        local targets = gs("RENDER_TARGETS")
        local paths = {}
        for f in (targets .. ";"):gmatch("([^;]+);") do paths[#paths + 1] = f end
        if #paths == 0 then fail("nothing to render (empty bounds?)") end
        -- an existing output file makes REAPER show a modal "overwrite?" dialog, which would block
        -- the bridge: refuse, or delete the old file first when overwrite=true
        for _, f in ipairs(paths) do
            if reaper.file_exists(f) then
                if not p.overwrite then fail("output file exists: %s (pass overwrite=true or another file_name)", f) end
                local ok, err = os.remove(f)
                if not ok then fail("can't overwrite %s: %s", f, tostring(err)) end
            end
        end
        reaper.Main_OnCommand(42230, 0)     -- File: Render project, using the most recent render settings, auto-close render dialog
        local files = {}
        for _, f in ipairs(paths) do files[#files + 1] = {path = f, exists = reaper.file_exists(f)} end
        return {files = list(files)}
    end)
    gs("RENDER_FILE", saved.file, true); gs("RENDER_PATTERN", saved.pattern, true)
    gs("RENDER_FORMAT", saved.format, true); gn("RENDER_BOUNDSFLAG", saved.bounds, true)
    gn("RENDER_STARTPOS", saved.s, true); gn("RENDER_ENDPOS", saved.e, true)
    gn("RENDER_SRATE", saved.srate, true); gn("RENDER_CHANNELS", saved.chans, true)
    gn("RENDER_TAILFLAG", saved.tail, true); gn("RENDER_SETTINGS", saved.settings, true)
    if not ok then error(res, 0) end
    local missing = 0
    for _, f in ipairs(res.files) do if not f.exists then missing = missing + 1 end end
    if #res.files == 0 or missing > 0 then fail("render finished but %d of %d output files are missing", missing, #res.files) end
    return res
end

local FREEZE = {stereo = {41223, "freeze to stereo"}, mono = {40901, "freeze to mono"},
                multichannel = {40877, "freeze to multichannel"}}

local function with_tracks(refs, fn)
    local sel = {}
    for i = 0, reaper.CountSelectedTracks(0) - 1 do sel[#sel + 1] = reaper.GetSelectedTrack(0, i) end
    for i = 0, reaper.CountTracks(0) - 1 do reaper.SetTrackSelected(reaper.GetTrack(0, i), false) end
    local trs = {}
    for i = 1, array_len(refs) do trs[#trs + 1] = get_track(refs[i]); reaper.SetTrackSelected(trs[#trs], true) end
    if #trs == 0 then fail("tracks is required") end
    local ok, err = pcall(fn, trs)
    for i = 0, reaper.CountTracks(0) - 1 do reaper.SetTrackSelected(reaper.GetTrack(0, i), false) end
    for _, t in ipairs(sel) do if reaper.ValidatePtr2(0, t, "MediaTrack*") then reaper.SetTrackSelected(t, true) end end
    if not ok then error(err, 0) end
    return trs
end

local function frozen_count(tr) return reaper.BR_GetMediaTrackFreezeCount and reaper.BR_GetMediaTrackFreezeCount(tr) or nil end

H.track_freeze = function(p)
    local f = FREEZE[opt(p.mode, "stereo")] or fail("mode must be stereo, mono or multichannel")
    local trs = with_tracks(p.tracks, function() RUN_CHECKED_ACTION(f[1], f[2]) end)
    local out = {}
    for _, tr in ipairs(trs) do out[#out + 1] = {track = track_index(tr), items = reaper.CountTrackMediaItems(tr),
                                                fx = reaper.TrackFX_GetCount(tr)} end
    return {frozen = list(out)}
end

H.track_unfreeze = function(p)
    local trs = with_tracks(p.tracks, function() RUN_CHECKED_ACTION(41644, "unfreeze") end)
    local out = {}
    for _, tr in ipairs(trs) do out[#out + 1] = {track = track_index(tr), items = reaper.CountTrackMediaItems(tr),
                                                fx = reaper.TrackFX_GetCount(tr)} end
    return {unfrozen = list(out)}
end

end
-- >>> 90_action.lua
do
-- Actions (main section)

local function resolve_command(c)
    if type(c) == "number" then return math.tointeger(c) end
    if type(c) == "string" then
        if c:match("^%d+$") then return math.tointeger(tonumber(c)) end
        local id = reaper.NamedCommandLookup(c:sub(1, 1) == "_" and c or ("_" .. c))
        if id == 0 then fail("unknown named command '%s'", c) end
        return id
    end
    fail("command must be an id or a named command string like '_SWS_ABOUT'")
end

local function action_name(id) return reaper.kbd_getTextFromCmd(id, reaper.SectionFromUniqueID(0)) or "" end

H.action_run = function(p)
    local id = resolve_command(p.command)
    local name = action_name(id)
    if name == "" then fail("no action with id %d", id) end
    reaper.Main_OnCommand(id, 0)
    return {id = id, name = name, state = reaper.GetToggleCommandState(id)}
end

H.action_find = function(p)
    local words = {}
    for w in (p.query or ""):lower():gmatch("%S+") do words[#words + 1] = w end
    if #words == 0 then fail("query is required") end
    local sec = reaper.SectionFromUniqueID(0)
    local out, i, limit = {}, 0, opt(p.limit, 50)
    while #out < limit do
        local id, name = reaper.kbd_enumerateActions(sec, i)
        if not id or id == 0 then break end
        local lname, hit = name:lower(), true
        for _, w in ipairs(words) do if not lname:find(w, 1, true) then hit = false break end end
        if hit then
            local named = reaper.ReverseNamedCommandLookup(id)
            out[#out + 1] = {id = id, name = name, named_command = named and ("_" .. named) or NULL,
                             state = reaper.GetToggleCommandState(id)}
        end
        i = i + 1
    end
    return {actions = list(out)}
end

H.action_state = function(p)
    local id = resolve_command(p.command)
    return {id = id, name = action_name(id), state = reaper.GetToggleCommandState(id)}
end

end
-- >>> 99_main.lua
-- REAPER MCP bridge - request loop. Source file; bundled by scripts/build_bridge.py.

local bridge_dir = reaper.GetResourcePath() .. '/Scripts/mcp_bridge_data/'

local function read_file(path)
    local f = io.open(path, "rb"); if not f then return nil end
    local s = f:read("a"); f:close(); return s
end

local function write_file(path, s)
    -- write to a temp name and rename, so the client never reads a half-written response
    local tmp = path .. ".tmp"
    local f = io.open(tmp, "wb"); if not f then return false end
    f:write(s); f:close()
    os.remove(path)
    return os.rename(tmp, path)
end

-- request ids are unique per server process (random base): list the directory
local function pending_request_ids()
    local ids, idx = {}, 0
    while true do
        local name = reaper.EnumerateFiles(bridge_dir, idx)   -- idx 0 forces a rescan
        if not name then break end
        local id = name:match("^request_(%d+)%.json$")
        if id then ids[#ids + 1] = id end
        idx = idx + 1
    end
    table.sort(ids, function(a, b) return #a < #b or (#a == #b and a < b) end)
    return ids
end

local DEBUG = reaper.GetExtState("MCP_BRIDGE", "debug") == "1"

local function handle(request)
    local func = request.func
    local args = request.args or json_array({}, 0)
    local n = resolve_args(args)
    local h = H[func]
    if not h then return {ok = false, error = "Unknown function: " .. tostring(func)} end
    local res = h(table.unpack(args, 1, n))
    if type(res) ~= "table" then res = {ret = res} end
    if res.ok == nil then res.ok = true end
    return res
end

local function process_requests()
    for _, id in ipairs(pending_request_ids()) do
        local req_path = bridge_dir .. "request_" .. id .. ".json"
        local resp_path = bridge_dir .. "response_" .. id .. ".json"
        local raw = read_file(req_path)
        os.remove(req_path)
        if raw then
            local response
            local ok, err = pcall(function()
                local request = decode_json(raw)
                if type(request) ~= "table" or not request.func then error("malformed request", 0) end
                if DEBUG then reaper.ShowConsoleMsg("MCP <- " .. raw:sub(1, 300) .. "\n") end
                response = handle(request)
            end)
            if not ok then response = {ok = false, error = tostring(err)} end
            local out = encode_json(response)
            if DEBUG then reaper.ShowConsoleMsg("MCP -> " .. out:sub(1, 300) .. "\n") end
            write_file(resp_path, out)
        end
    end
end

reaper.RecursiveCreateDirectory(bridge_dir, 0)

-- Opt-in hot reload for development: with ExtState MCP_BRIDGE/autoreload = "1" the bridge
-- re-runs its own script file when it changes (checked once a second). Each load bumps a
-- generation counter; the previous loop sees it and stops.
MCP_BRIDGE_GEN = (MCP_BRIDGE_GEN or 0) + 1
local my_gen = MCP_BRIDGE_GEN
local script_path = (debug.getinfo(1, "S").source or ""):match("^@(.+)$")
local loaded_src = script_path and read_file(script_path)
local last_check = reaper.time_precise()

local function maybe_reload()
    if reaper.GetExtState("MCP_BRIDGE", "autoreload") ~= "1" or not loaded_src then return false end
    local now = reaper.time_precise()
    if now - last_check < 1 then return false end
    last_check = now
    local src = read_file(script_path)
    if not src or src == loaded_src then return false end
    loaded_src = src
    local chunk, err = load(src, "@" .. script_path)
    if not chunk then
        reaper.ShowConsoleMsg("MCP bridge: reload failed, keeping the running version: " .. tostring(err) .. "\n")
        return false
    end
    reaper.ShowConsoleMsg("MCP bridge: source changed, reloading\n")
    chunk()
    return true
end

reaper.ShowConsoleMsg(string.format("REAPER MCP bridge started (gen %d, %s)\n", my_gen, bridge_dir))

local function loop()
    if MCP_BRIDGE_GEN ~= my_gen then return end   -- superseded by a reload
    process_requests()
    if maybe_reload() then return end
    reaper.defer(loop)
end
loop()

