#!/usr/bin/env python3
"""Bundle lua/src/*.lua into lua/mcp_bridge.lua (the single file REAPER runs).

Order: 00_core.lua first, domain files (10_*.lua ... 89_*.lua) each wrapped in do...end so
their local helpers stay private, 99_main.lua last.  Usage: python3 scripts/build_bridge.py [--check]
"""
import pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC, OUT = ROOT / "lua" / "src", ROOT / "lua" / "mcp_bridge.lua"


def bundle() -> str:
    files = sorted(SRC.glob("*.lua"))
    core = [f for f in files if f.name.startswith("00_")]
    main = [f for f in files if f.name.startswith("99_")]
    domains = [f for f in files if f not in core + main]
    parts = ["-- GENERATED by scripts/build_bridge.py from lua/src/*.lua - do not edit by hand.\n"]
    for f in core:
        parts.append(f"-- >>> {f.name}\n{f.read_text(encoding='utf-8')}\n")
    for f in domains:
        parts.append(f"-- >>> {f.name}\ndo\n{f.read_text(encoding='utf-8')}\nend\n")
    for f in main:
        parts.append(f"-- >>> {f.name}\n{f.read_text(encoding='utf-8')}\n")
    return "".join(parts)


if __name__ == "__main__":
    text = bundle()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        sys.exit(0 if current == text else "lua/mcp_bridge.lua is out of date - run scripts/build_bridge.py")
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
